select COCOMER  CODIGO, CODENO DENOMINACION, AFCODI ACTIVOFIJO, AFSERN NROSERIAL,
(CASE WHEN COCONEX = 0 THEN '*****' WHEN COCONEX = 1 THEN 'DIAL' WHEN COCONEX = 2 THEN 'LAN'
 WHEN COCONEX =3 THEN 'DIAL Y LAN' WHEN COCONEX =4 THEN 'INALAMBRICO'
WHEN COCONEX =5 THEN '*****' WHEN COCONEX =6 THEN 'INALAMBRICO Y DIAL' WHEN COCONEX = 7 THEN 'INALAMBRICO - LAN - DIAL' END) 
tipo_conex,AFAPPVER version, 'ACTIVO' estado
--select * from gxbdbps.coaftaf
-- C.AFTIDESC DESCRIPCION
from GXBDBPS.COMAEAF A
INNER JOIN gxbdbps.COAFMAF B ON (AFCOMER = COCOMER)
INNER JOIN GXBDBPS.COAFTAF  C ON  B.AFTICODI = C.AFTICODI
WHERE  SUBSTR(COCOMER,1,2) NOT IN ('90', '95', '99')  
and cocomer <> '0100001' 

