select * from  CONTABILID.GE04NIV where nicous='U99DENISSE';
insert INTO CONTABILID.GE04NIV (NICOUS, NISIST, NINIVE) values ('U99DENISSE', 'CC','FA');
insert INTO CONTABILID.GE04NIV (NICOUS, NISIST, NINIVE) values ('U99DENISSE', 'CC','GE');
insert INTO CONTABILID.GE04NIV (NICOUS, NISIST, NINIVE) values ('U99DENISSE', 'CC','G1');
insert INTO CONTABILID.GE04NIV (NICOUS, NISIST, NINIVE) values ('U99DENISSE', 'CC','G2');
insert INTO CONTABILID.GE04NIV (NICOUS, NISIST, NINIVE) values ('U99DENISSE', 'CC','G3');
insert INTO CONTABILID.GE04NIV (NICOUS, NISIST, NINIVE) values ('U99DENISSE', 'CC','G4');
insert INTO CONTABILID.GE04NIV (NICOUS, NISIST, NINIVE) values ('U99DENISSE', 'CC','G5');
insert INTO CONTABILID.GE04NIV (NICOUS, NISIST, NINIVE) values ('U99DENISSE', 'CC','G9');
insert INTO CONTABILID.GE04NIV (NICOUS, NISIST, NINIVE) values ('U99DENISSE', 'CC','IG');

select * from contabilid.ge03acc where accous='U99DENISSE'
INSERT INTO CONTABILID.GE03ACC (ACCOUS, ACPROG, ACOPER) values ('U99DENISSE', 'CC302R', '');
INSERT INTO CONTABILID.GE03ACC (ACCOUS, ACPROG, ACOPER) values ('U99DENISSE', 'CC303R', '');

select * from contabilid.tatacus where tacous='U99DENISSE';
INSERT INTO CONTABILID.TATACUS (TACOUS, TASUCU, TAAREA, TADEPA) values ('U99DENISSE', '01', '02', '0');

