SELECT lcodbc, codmar, lidcom, a.LENEMI COD_ENTIDAD, LCODBC MARCA, LCPACE PRODUCTO, LTIPTR TIPO_TARJETA , LMARCA AMBITO , LBINPR BIN, SUBSTR(lnrtar,1,6)||'XXXXXX'||SUBSTR(lnrtar,13,4) TARJETA,
LFECTR FECHA_REAL, lfcotr FECHA_COMERCIAL, LHORTR HORA, LCODTR COD_TRX,
txdtrx DESC_TRX, LNFISC BIN_ADQUIRENTE, LPOSEM COD_ENTRADA,
(CASE WHEN LPOSEM in ('9010','9020','910','920') THEN 'BANDA MAGNETICA'
WHEN LPOSEM = '0510' THEN 'CHIP'
WHEN LPOSEM = '0710' THEN 'CONTACLESS'
WHEN LPOSEM = '0100' THEN 'PAN Manual Entry'
when LPOSEM= '0120' then 'PAN Manual Entry'
when LPOSEM='1000' then 'Credential on File'
when LPOSEM= '1020' then 'Credential on FIle'
when LPOSEM= '8010' then 'Fallback' else 'VACIO' END) MODO_ENTRADA,
LMCCTR TIPO_DE_COMERCIO , lidcom COD_COMERCIO, LCOMTR DENOMINACION, codtodesc DEPARTAMENTO, LODESC LOCALIDAD, limpgs IMPORTE,
SUBSTR(LIDTRA,1,1) DISPOSITIVO, LECA62 VERSION, LESTTR ESTADO, LCRETR RESPUESTA, CODDES DESCRIP_RESP, LCAUTR AUTORIZACION, LERRNB REFERENCIA,
LCUOTA CUOTA
FROM TESTDB.DRCONBEP a
inner join TESTDB.tbctra0p on txctrx = lcodtr
INNER JOIN TESTDB.TBCRET0P ON CODNRO = LCRETR
inner join TESTDB.comaeaf d on substr(digits(a.lidcom), 6, 7)=d.cocomer
inner join TESTDB.colocaf k on d.locodi = k.locodi
  INNER JOIN TESTDB.CODTOAF X ON (k.CODDTO = X.CODDTO)
WHERE LERRNB IN (200121125109, 200121125109)
and substr(lidtra,1,1) = 'P'
AND LCODBC= 'MST'
AND CODMAR = 'BEPS'
AND LENEMI IN ('530')
AND LIDCOM <> '100001'
order by LFECTR


select * from TESTDB.DRCONBEP WHERE LERRNB ='200121125109'
