*SISTEMA DE ADMINISTRACION DE SEGURIDAD*/
SELECT GXBDCON.GXLOUSU.USUCOD, GXBDCON.GXLOUSU.USUNOM, GXBDCON.GXLOUSU.USUAID, GXBDCON.GXLOUSU.USUMAI, GXBDCON.GXLOUSU.USUEST,
GXBDCON.GXLOPERDET.SISCODI,
GXBDCON.GXLOSIS.SISNOM,
GXBDCON.GXLOPERDET.FUNCOD,
GXBDCON.GXLOFUN.FUNDES,
GXBDCON.GXLOPERDET.PERDSP,
GXBDCON.GXLOPERDET.PERUPD,--*SISTEMA DE ADMINISTRACION DE SEGURIDAD*/
SELECT GXBDCON.GXLOUSU.USUCOD, GXBDCON.GXLOUSU.USUNOM, GXBDCON.GXLOUSU.USUAID, GXBDCON.GXLOUSU.USUMAI, GXBDCON.GXLOUSU.USUEST,
GXBDCON.GXLOPERDET.SISCODI,
GXBDCON.GXLOSIS.SISNOM,
GXBDCON.GXLOPERDET.FUNCOD,
GXBDCON.GXLOFUN.FUNDES,
GXBDCON.GXLOPERDET.PERDSP,
GXBDCON.GXLOPERDET.PERUPD,
GXBDCON.GXLOPERDET.PERINS,
GXBDCON.GXLOPERDET.PERDLT
FROM GXBDCON.GXLOUSU
INNER JOIN GXBDCON.GXLOPERDET ON GXBDCON.GXLOUSU.USUCOD=GXBDCON.GXLOPERDET.USUCOD 
INNER JOIN GXBDCON.GXLOSIS ON GXBDCON.GXLOPERDET.SISCODI=GXBDCON.GXLOSIS.SISCODI
INNER JOIN GXBDCON.GXLOFUN ON GXBDCON.GXLOPERDET.FUNCOD=GXBDCON.GXLOFUN.FUNCOD
WHERE GXBDCON.GXLOUSU.USUAID='$[USUARIO]';

GXBDCON.GXLOPERDET.PERINS,
GXBDCON.GXLOPERDET.PERDLT
FROM GXBDCON.GXLOUSU
INNER JOIN GXBDCON.GXLOPERDET ON GXBDCON.GXLOUSU.USUCOD=GXBDCON.GXLOPERDET.USUCOD 
INNER JOIN GXBDCON.GXLOSIS ON GXBDCON.GXLOPERDET.SISCODI=GXBDCON.GXLOSIS.SISCODI
INNER JOIN GXBDCON.GXLOFUN ON GXBDCON.GXLOPERDET.FUNCOD=GXBDCON.GXLOFUN.FUNCOD
WHERE GXBDCON.GXLOUSU.USUAID='$[USUARIO]';
