--Tarea_91752
--Query R_Conti (DB2)
SELECT TRIM(T.AUTRRNBEP) AS REFERENCIA,
T.AUTTRXFCHF AS FECHA_REAL,
T.AUTTRXFCHC AS FECHA_PROCESO,
T.AUTTRXHORF AS HORA,
SUBSTR(TRIM(T.AUTPANNRO),1,6)||'XXXXXX'||SUBSTR(TRIM(T.AUTPANNRO),LENGTH(TRIM(T.AUTPANNRO))-4+1) AS TARJETA,
TRIM(T.AUTMARTAR) AS MARCA,
T.AUTMONORI AS MONEDA_ORIGEN,
T.AUTMONTDES AS IMPORTE,
T.AUTCODAUT AS COD_AUTORIZACION,
TRIM(T.AUTCODSER) AS SERVICIO,
TRIM(T.AUTCODPRE) AS PRESTACION,
CAST(T.AUTCODCLI AS VARCHAR(7)) AS COD_CLIENTE,
CAST(T.AUTCODSUC AS VARCHAR(5)) AS COD_SUCURSAL,
TRIM(T.AUTCOMRAZ) AS SUCURSAL,
'T'||SUBSTR(TRIM(T.AUTCODCOMB),5,3) AS NROATM
FROM GXBDBPS.TSWAUT t
WHERE
T.AUTTRXFCHC BETWEEN (SELECT FECANT FROM GXFINDTA.TCLFEC t WHERE T.FECID = '002') AND (SELECT FECPRO FROM GXFINDTA.TCLFEC t WHERE T.FECID = '002')
AND T.AUTTRXESTF = 'A' AND T.AUTCODRET = '00'
AND SUBSTR(TRIM(t.AUTTRXFCHC),1,4)CONCAT'-'CONCAT SUBSTR(TRIM(t.AUTTRXFCHC),5,2)CONCAT'-'CONCAT SUBSTR(TRIM(t.AUTTRXFCHC),7)CONCAT' 'CONCAT TRIM(t.AUTTRXHORF)
BETWEEN (SELECT  SUBSTR(TRIM(FECANT),1,4)CONCAT'-'CONCAT SUBSTR(TRIM(FECANT),5,2)CONCAT'-'CONCAT SUBSTR(TRIM(FECANT),7)CONCAT' 19:00:00'
FROM GXFINDTA.TCLFEC t WHERE T.FECID = '002') AND (SELECT  SUBSTR(TRIM(FECPRO),1,4)CONCAT'-'CONCAT SUBSTR(TRIM(FECPRO),5,2)CONCAT'-'CONCAT SUBSTR(TRIM(FECPRO),7)CONCAT' 18:59:59'
FROM GXFINDTA.TCLFEC t WHERE T.FECID = '002')
AND SUBSTRING(t.AUTENTADM,1,4 ) = '1020'
AND t.AUTCODSER = 'ADELANTO';

--Query Remanentes (Confirmar corte primeramente - si es posible desde el atmcentre)
SELECT
b.NA_BRANCH COMPAÑIA
,x1.ID_TERMINAL CAJERO
,'UNK' ULT_ABASTECIMIENTO
,FORMAT(x1.DT_EJM_SYSTEM_CUT,'yyyy-MM-dd') FECHA
,CASE
WHEN m.CD_CASSETTE = 'A' THEN 1
WHEN m.CD_CASSETTE = 'B' THEN 2
WHEN m.CD_CASSETTE = 'C' THEN 3
WHEN m.CD_CASSETTE = 'D' THEN 4
WHEN m.CD_CASSETTE = 'E' THEN 5
ELSE 0
END CASETERO
,m.CD_CASSETTE_CASH_CURR MONEDA
,m.CD_CASSETTE_CASH_DENOM DENOMINACION
,m.QT_INIT_CASSETTE_CASH CANTIDAD_INICIAL
,m.QT_INC_CASSETTE_CASH ADICION
,m.QT_DISP_CASSETTE_CASH RETIROS
,m.QT_REJEC_CASSETTE_CASH RECHAZADOS
,m.QT_INIT_CASSETTE_CASH+m.QT_INC_CASSETTE_CASH-m.QT_DISP_CASSETTE_CASH-m.QT_REJEC_CASSETTE_CASH RESTANTES
FROM atmcentre01.dbo.EJM_SYSTEM_CUT_CASSETTE m
INNER JOIN atmcentre01.dbo.EJM_SYSTEM_CUT x1
ON m.ID_EJM_SYSTEM_CUT = x1.ID_EJM_SYSTEM_CUT
INNER JOIN atmcentre01.dbo.BRANCH b ON
x1.ID_BRANCH = b.ID_BRANCH
WHERE
x1.ID_TERMINAL LIKE '%T020%' --Entidad Conti
AND x1.DT_EJM_SYSTEM_CUT >= CONVERT(DATETIME,FORMAT(DATEADD(DAY, -1,CURRENT_TIMESTAMP),'yyyy-MM-dd')+' 00:00:00.000', 120)
AND x1.DT_EJM_SYSTEM_CUT < CONVERT(DATETIME,FORMAT(DATEADD(DAY, -1,CURRENT_TIMESTAMP),'yyyy-MM-dd')+' 23:59:59.999', 120)
ORDER BY x1.DT_EJM_SYSTEM_CUT DESC , x1.ID_TERMINAL