--91524
SELECT SUBSTR(M.DETFEC, 1, 8)                                                                                            FECHA_CIERRE,
       SUBSTR(M.DETCUEN, 1, 11)                                                                                          CUENTA,
       SUBSTR(0, 1, 4)                                                                                                   SECUENCIA,
       M.DETNTAR                                                                                                         TARJETA,
       SUBSTR(M.DETCUSU, 1, 15)                                                                                          CUPON,
       SUBSTR(M.DETMUSU, 1, 15)                                                                                          MOV_USUARIO,
       SUBSTR(M.DETTSAL, 1, 2)                                                                                           TIPO_SALDO,
       SUBSTR(M.DETTCAR, 1, 3)                                                                                           TIPO_CARGO,
       M.DETATCA                                                                                                         AGRUP_TIP_CAR,
       SUBSTR(M.DETFECO, 1, 8)                                                                                           FECHA_OPERACION,
       SUBSTR(M.DETFPRO, 1, 8)                                                                                           FECHA_PROCESO,
       SUBSTR(M.DETNROC, 1, 15)                                                                                          NRO_CUPON,
       SUBSTR(M.DETDSCO, 1, 40)                                                                                          DESC_OPER,
       REPLACE(CAST(M.DETIMPL AS CHAR(15)), '.', ',')                                                                    IMPORTE_OPER,
       M.DETMLIQ                                                                                                         MONEDA,
       M.DETCODP                                                                                                         COD_PLANES,
       LPAD(M.DETNCUO, 2, ' ')                                                                                           NRO_CUOTA,
       LPAD(M.DETCCUO, 3, ' ')                                                                                           CANT_CUOTAS,
       REPLACE(CAST(M.DETICUO AS CHAR(15)), '.', ',')                                                                    INTERES_CUOTA,
       LPAD(M.DETESTC, 1, ' ')                                                                                           ESTADO_CUOTA,
       SUBSTR(M.DETDSCE, 1, 15)                                                                                          DESC_EST_CUOTA,
       M.DETCALI                                                                                                         FORMA_CAL_IVA,
       SUBSTR(M.DETFCAI, 1, 30)                                                                                          DESC_FORM_CALC,
       M.DETIMPM                                                                                                         IMPUESTO_MOV,
       REPLACE(CAST(CAST(M.DETIMPI AS DECIMAL(15, 2)) AS CHAR(15)), '.', ',')                                            IMPORTE_IMPUESTO,
       SUBSTR(CAST(M.DETPORI AS DECIMAL(8, 0)), 1, 8)                                                                    PORCENTAJE_IMPUESTO,
       SUBSTR(M.DETOTRX, 1, 8)                                                                                           ORIGEN_TRX,
       REPLACE(CAST(M.DETIMPO AS CHAR(15)), '.', ',')                                                                    IMPORTE_ORIGEN,
       M.DETMONI                                                                                                         MONEDA_ORIGEN,
       M.DETPAIS                                                                                                         PAIS_ORIGEN,
       SUBSTR(M.DETLOCC, 1, 40)                                                                                          LOCALIDAD_COMERCIO,
       M.DETFPM                                                                                                          FINANCIAR_PM,
       SUBSTR(M.DETIPM, 1, 15)                                                                                           TIPIF_MOV,
       SUBSTR(CAST(M.DETENT AS DECIMAL(3)), 1, 3)                                                                        COD_ENTIDAD,
       M.DETMAR                                                                                                          COD_MARCA,
       M.DETPRO                                                                                                          COD_PRODUCTO,
       SUBSTR(M.DETAFI, 1, 6)                                                                                            AFINIDAD,
       SUBSTR(M.DETNRLC, 1, 15)                                                                                          NUMERAL,
       M.DETCATM                                                                                                         CANT_TRX,
       SUBSTR(M.DEFULTA, 1, 4) || '-' || SUBSTR(M.DEFULTA, 5, 2) || '-' || SUBSTR(M.DEFULTA, 7, 2) || '-00.00.00.000000' FEC_HRA_ULT,
       SUBSTR(M.DETMGEN, 1, 15)                                                                                          MOMENTO_GENERACION,
       M.DETITC                                                                                                          TIPO_CIERRE,
       M.DETAFD                                                                                                          AFECTACION_DETALLE,
       SUBSTR(M.DETIIC, 1, 3)                                                                                            IMPUESTO_TPO,
       M.DETMNA                                                                                                          MOTIVO,
       SUBSTR(M.DETTRU, 1, 2)                                                                                            ID_RUBRO,
       SUBSTR(M.DETAGR, 1, 3)                                                                                            COD_AGRU_EXTR,
       SUBSTR(M.DETOAE, 1, 3)                                                                                            ORDEN_EXTR,
       SUBSTR(M.DETARJ, 1, 20)                                                                                           TIPO_TAR
FROM GXBDBPS.MAEEXTDET M
WHERE M.DETFEC = '20250403'
  AND M.DETENT = '021'
ORDER BY M.DETID;