--Mov 021/176

WITH MOV AS
(SELECT
	T1 . MVSECUE MOVNREF ,  --30-NRO REF,
	T1 . MVEMISO MOVENT ,  --1-ENTIDAD,
	T1 . MVFEPRO MOVFECC ,  --20- FEC COMERCIAL,
	T1 . MVAFINI MOVAFI ,  --2-AFINIDAD,
	T1 . MVNUMCT MOVCTA ,  --3-CUENTA,
	T2 . MCNUMDO MOVDOC ,  -- 4-CEDULA DE IDENTIDAD
	T1 . MTNUMTA MOVNUMTA ,  --5-NRO DE TARJETA,
	T1 . MVTIPTA MOVTIPTA ,  --6-TIPO DE TC,
	T1 . MVCODSC MOVSUC ,  --7-SUC DE LA TC,
--	COALESCE ( T3 . CESEXO , 'M' ) MOVSEX,  -- 8- SEX DEL CLIENTE
( CASE
WHEN T3 . CESEXO = '' OR T3 . CESEXO IS NULL THEN
'M'
ELSE
T3 . CESEXO
END ) MOVSEX ,
	T1 . CMCODIG MOVCODM ,  --9-COD MOV
	T4 . CMDESCR MOVDESM ,  --10-DESCRIP MOV,
	T4 . CMTIPOM MOVTIPOM ,  --11- TIPO MOV,
	T4 . CMSAFAC MOVASALF ,  --12-AFECTA A SALDO A F,
	T4 . CMSFNVE MOVASFNV ,  --13-AFECTA SALDO FNV,
	T4 . CMSALFI MOVSALFI ,  --14-AFECTA SALDO FI,
	T4 . CMCUOPE MOVACUP ,  --15-AFECTA CUOTAS PEND,
	T4 . CMADEPE MOVACUAP ,  --16-AFECTA CUOTA ADELANTO PEND,
	T4 . CMREFPE MOVACURP ,  --17- AFECTA CUOTA DE REF PEND,
	T4 . CMAPAGO MOVACUMP ,  --18-AFECTA ACUM PAGOS,
	T1 . MVFEREA MOVFECR ,  --19-FEC REAL,
	( CASE DAYOFWEEK ( DATE ( SUBSTRING ( CHAR ( T1 . MVFEREA ) , 1 , 4 ) || '-' || SUBSTRING ( CHAR ( T1 . MVFEREA ) , 5 , 2 ) || '-' || SUBSTRING ( CHAR ( T1 . MVFEREA ) , 7 , 2 ) ) )
			WHEN 1 THEN 'Domingo'
			WHEN 2 THEN 'Lunes'
			WHEN 3 THEN 'Martes'
			WHEN 4 THEN 'Miercoles'
			WHEN 5 THEN 'Jueves'
			WHEN 6 THEN 'Viernes'
			WHEN 7 THEN 'Sabado'
		END ) MOVDIAS ,  --21Dia de la semana
	T1 . MVIMPO2 MOVIMPO ,  --22-IMPORTE SIN DECIMALES,
	T1 . MVCODCO MOVCODC ,  --23- COD COMERCIO,
	REPLACE ( ( REPLACE ( ( REPLACE ( ( REPLACE ( ( REPLACE ( ( REPLACE ( ( REPLACE ( T1 . MVNOMCO , 'Ñ' , 'N' ) ) , '*' , ' ' ) ) , '?' , ' ' ) ) , ',' , ' ' ) ) , '"' , ' ' ) ) , '''' , ' ' ) ) , ';' , ' ' ) MOVDESC ,  --24-DESCRIP COMERCI
--O
	COALESCE ( T5 . RUDESC , 'TODOS' ) MOVRUB ,  --25-RUBRO,
	COALESCE ( T7 . LODESC , 'TODOS' ) MOVLOCC ,  --26-LOCALIDAD COM,
	COALESCE ( T6 . CORUCN , ' ' ) MOVRUCC ,  --27-RUC COMER,
	COALESCE ( T1 . MVMECAC , ' ' ) MOVMCC ,  --28-MCC,
	'000' MOVCANCU ,  --29-CANT CUOTAS,
	T1 . MVCODAU MOVCODAU ,  --31-COD AUTORIZACION,
	T1 . MVIDUSR MOVUSU ,  --32- USU QUE IMPUTO,
	COALESCE ( T8 . MEPIDPROMO , '0' ) MOVPROMO ,  --33-ID PROMO,
	T1 . MVCUPON MOVCUPON ,  --34-COD CUPON,
	CASE
		WHEN T8 . MEPNROCOMP <> ''
			THEN T8 . MEPNROCOMP
		ELSE
			T1 . MVSECUE
	END MOVCOMPG ,  --35-COMPROBANTE PAGO APIS
	'T' MOVTIP
	FROM ( ( ( ( ( ( ( GXBDBPS . TMOVIAF T1
	INNER JOIN GXBDBPS . TMCTAAF T2 ON T1 . MVNUMCT = T2 . MCNUMCT )
	LEFT JOIN GXBDBPS . GCLIEAF T3 ON T2 . MCTIPOD = T3 . CETIPOD AND T2 . MCNUMDO = T3 . CENUMDO AND T1 . MVEMISO = T3 . ENEMISO )
	INNER JOIN GXBDBPS . TCMOVAF T4 ON T1 . CMCODIG = T4 . CMCODIG )
	LEFT JOIN GXBDBPS . CORUBAF T5 ON SUBSTRING ( T1 . MVCODCO , 1 , 2 ) = T5 . RUCODI )
	LEFT JOIN GXBDBPS . COMAEAF T6 ON T1 . MVCODCO = T6 . COCOMER )
	LEFT JOIN GXBDBPS . COLOCAF T7 ON T6 . LOCODI = T7 . LOCODI )
	LEFT JOIN GXTRJDTA . TMOMEP T8 ON T8 . MEPIDCTA = T1 . MVNUMCT AND T8 . MEPIDMOVCL = T1 . MVCUPON AND T1 . MVCUPON <> 0 AND T8 . MEPFCHPRO = T1 . MVFEPRO )
	WHERE T1 . MVCODRE = 0 AND T1 . MVEMISO IN ('021','176') AND T1 . MVFEPRO >= '20230101'
	AND T1.CMCODIG = '579'--NOT IN ( '123' , '103' , '104' , '124' , '105' , '125' , '106' , '126' , '107' , '127' , '011' ) AND ( T1 . CMCODIG < '900' )
UNION ALL
SELECT
	T1 . CUMVSEC MOVNREF ,  --30-NRO REF,
	T1 . CUEMISO MOVENT ,  --1-ENTIDAD,
	T1 . CUFECOM MOVFECC ,  --20- FEC COMERCIAL,
	T1 . CUAFINI MOVAFI ,  --2-AFINIDAD,
	T1 . CUNUMCT MOVCTA ,  --3-CUENTA,
	T2 . MCNUMDO MOVDOC ,  -- 4-CEDULA DE IDENTIDAD
	T1 . MTNUMTA MOVNUMTA ,  --5-NRO DE TARJETA,
	T3 . MTTIPOT MOVTIPTA ,  --6-TIPO DE TC,
	T1 . CUCODSC MOVSUC ,  --7-SUC DE LA TC,
--	COALESCE ( T4 . CESEXO , 'M' ) MOVSEX ,  -- 8- SEX DEL CLIENTE
( CASE
WHEN T4 . CESEXO = '' OR T4 . CESEXO IS NULL THEN
'M'
ELSE
T4 . CESEXO
END ) MOVSEX ,
	T1 . CMCODIG MOVCODM ,  --9-COD MOV,
	T5 . CMDESCR MOVDESM ,  --10-DESCRIP MOV,
	T5 . CMTIPOM MOVTIPOM ,  --11- TIPO MOV,
	T5 . CMSAFAC MOVASALF ,  --12-AFECTA A SALDO A F,
	T5 . CMSFNVE MOVASFNV ,  --13-AFECTA SALDO FNV,
	T5 . CMSALFI MOVSALFI ,  --14-AFECTA SALDO FI,
	T5 . CMCUOPE MOVACUP ,  --15-AFECTA CUOTAS PEND,
	T5 . CMADEPE MOVACUAP ,  --16-AFECTA CUOTA ADELANTO PEND,
	T5 . CMREFPE MOVACURP ,  --17- AFECTA CUOTA DE REF PEND,
	T5 . CMAPAGO MOVACUMP ,  --18-AFECTA ACUM PAGOS,
	T1 . CUFEREA MOVFECR ,  --19-FEC REAL,
	CASE DAYOFWEEK ( DATE ( SUBSTRING ( CHAR ( T1 . CUFEREA ) , 1 , 4 ) || '-' || SUBSTRING ( CHAR ( T1 . CUFEREA ) , 5 , 2 ) || '-' || SUBSTRING ( CHAR ( T1 . CUFEREA ) , 7 , 2 ) ) )
		WHEN 1 THEN 'Domingo'
		WHEN 2 THEN 'Lunes'
		WHEN 3 THEN 'Martes'
		WHEN 4 THEN 'Miercoles'
		WHEN 5 THEN 'Jueves'
		WHEN 6 THEN 'Viernes'
		WHEN 7 THEN 'Sabado'
	END MOVDIAS ,  --21Dia de la semana
	T1 . CUIMPOR MOVIMPO ,  --22-IMPORTE SIN DECIMALES,
	T1 . CUCODCO MOVCODC ,  --23- COD COMERCIO,
	REPLACE ( ( REPLACE ( ( REPLACE ( ( REPLACE ( ( REPLACE ( ( REPLACE ( ( REPLACE ( T1 . CUNOMCO , 'Ã?' , 'N' ) ) , '*' , ' ' ) ) , '?' , ' ' ) ) , ',' , ' ' ) ) , '"' , ' ' ) ) , '''' , ' ' ) ) , ';' , ' ' ) MOVDESC ,  --24-DESCRIP COMERC --IO
	COALESCE ( T6 . RUDESC , 'TODOS' ) MOVRUB ,  --25-RUBRO,
	COALESCE ( T8 . LODESC , 'TODOS' ) MOVLOCC ,  --26-LOCALIDAD COM,
	COALESCE ( T7 . CORUCN , ' ' ) MOVRUCC ,  --27-RUC COMER,
	COALESCE ( T6 . RUMCC , ' ' ) MOVMCC ,  --28-MCC,
	T1 . CUCANCU MOVCANCU ,  --29-CANT CUOTAS,
	T1 . CUCODAU MOVCODAU ,  --31-COD AUTORIZACION,
	T1 . CUIDUSR MOVUSU ,  --32- USU QUE IMPUTO,
	COALESCE ( T9 . CUPIDPRO , '0' ) MOVPROMO ,  --34-ID-PROMO
	COALESCE ( T9 . CUPCODI , '0' ) MOVCUPON ,  --NRO CUPON
	T1 . CUMVSEC MOVCOMPG ,  --35-COMPROBANTE PIN APIS
	'C' MOVTIP
	FROM GXBDBPS . TCUOTAF T1
	INNER JOIN GXBDBPS . TMCTAAF T2 ON T1 . CUNUMCT = T2 . MCNUMCT
	INNER JOIN GXBDBPS . TMTARAF T3 ON T1 . MTNUMTA = T3 . MTNUMTA
	LEFT JOIN GXBDBPS . GCLIEAF T4 ON T2 . MCTIPOD = T4 . CETIPOD AND T2 . MCNUMDO = T4 . CENUMDO AND T1 . CUEMISO = T4 . ENEMISO
	INNER JOIN GXBDBPS . TCMOVAF T5 ON T1 . CMCODIG = T5 . CMCODIG
	LEFT JOIN GXBDBPS . CORUBAF T6 ON SUBSTRING ( T1 . CUCODCO , 1 , 2 ) = T6 . RUCODI
	LEFT JOIN GXBDBPS . COMAEAF T7 ON T1 . CUCODCO = T7 . COCOMER
	LEFT JOIN GXBDBPS . COLOCAF T8 ON T7 . LOCODI = T8 . LOCODI
	LEFT JOIN GXFINDTA . TCLCUP T9 ON T9 . CUPNTAR = T1 . MTNUMTA AND T9 . CUPRRNMI = T1 . CUMVSEC AND T9 . CUPCOAU = T1 . CUCODAU AND T9 . CUPCOCO = T1 . CUCODCO	WHERE T1 . CUSTATS <> 'R'
	AND T1 . CUEMISO IN ('021','176') AND T1 . CUFECOM >= '20230101'	 AND
	T1 . CMCODIG = '579' --NOT IN ( '123' , '103' , '104' , '124' , '105' , '125' , '106' , '126' , '107' , '127' , '011' , '159' ) AND T1 . CMCODIG < '900'
UNION ALL
	SELECT
	T1 . HMSECUE MOVNREF ,  --30-NRO REF,
	T1 . HMEMISO MOVENT ,  --1-ENTIDAD,
	T1 . HMFEPRO MOVFECC ,  --20- FEC COMERCIAL,
	T1 . HMAFINI MOVAFI ,  --2-AFINIDAD,
	T1 . HMNUMCT MOVCTA ,  --3-CUENTA,
	T2 . MCNUMDO MOVDOC ,  -- 4-CEDULA DE IDENTIDAD
	T1 . HMNUMTA MOVNUMTA ,  --5-NRO DE TARJETA,
	T1 . HMTIPTA MOVTIPTA ,  --6-TIPO DE TC,
	T1 . HMCODSC MOVSUC ,  --7-SUC DE LA TC,
--	COALESCE ( T3 . CESEXO , 'M' ) MOVSEX ,  -- 8- SEX DEL CLIENTE
( CASE
WHEN T3 . CESEXO = '' OR T3 . CESEXO IS NULL THEN
'M'
ELSE
T3 . CESEXO
END ) MOVSEX ,
	T1 . HMCODIG MOVCODM ,  --9-COD MOV
	T4 . CMDESCR MOVDESM ,  --10-DESCRIP MOV,
	T4 . CMTIPOM MOVTIPOM ,  --11- TIPO MOV,
	T4 . CMSAFAC MOVASALF ,  --12-AFECTA A SALDO A F,
	T4 . CMSFNVE MOVASFNV ,  --13-AFECTA SALDO FNV,
	T4 . CMSALFI MOVSALFI ,  --14-AFECTA SALDO FI,
	T4 . CMCUOPE MOVACUP ,  --15-AFECTA CUOTAS PEND,
	T4 . CMADEPE MOVACUAP ,  --16-AFECTA CUOTA ADELANTO PEND,
	T4 . CMREFPE MOVACURP ,  --17- AFECTA CUOTA DE REF PEND,
	T4 . CMAPAGO MOVACUMP ,  --18-AFECTA ACUM PAGOS,
	T1 . HMFEREA MOVFECR ,  --19-FEC REAL,
	( CASE DAYOFWEEK ( DATE ( SUBSTRING ( CHAR ( T1 . HMFEREA ) , 1 , 4 ) || '-' || SUBSTRING ( CHAR ( T1 . HMFEREA ) , 5 , 2 ) || '-' || SUBSTRING ( CHAR ( T1 . HMFEREA ) , 7 , 2 ) ) )
			WHEN 1 THEN 'Domingo'
			WHEN 2 THEN 'Lunes'
			WHEN 3 THEN 'Martes'
			WHEN 4 THEN 'Miercoles'
			WHEN 5 THEN 'Jueves'
			WHEN 6 THEN 'Viernes'
			WHEN 7 THEN 'Sabado'
		END ) MOVDIAS ,  --21Dia de la semana
	T1 . HMIMPO2 MOVIMPO ,  --22-IMPORTE SIN DECIMALES,
	T1 . HMCODCO MOVCODC ,  --23- COD COMERCIO,
	REPLACE ( ( REPLACE ( ( REPLACE ( ( REPLACE ( ( REPLACE ( ( REPLACE ( ( REPLACE ( T1 . HMNOMCO , 'Ã?' , 'N' ) ) , '*' , ' ' ) ) , '?' , ' ' ) ) , ',' , ' ' ) ) , '"' , ' ' ) ) , '''' , ' ' ) ) , ';' , ' ' ) MOVDESC ,  --24-DESCRIP COMERC
	COALESCE ( T5 . RUDESC , 'TODOS' ) MOVRUB ,  --25-RUBRO,
	COALESCE ( T7 . LODESC , 'TODOS' ) MOVLOCC ,  --26-LOCALIDAD COM,
	COALESCE ( T6 . CORUCN , ' ' ) MOVRUCC ,  --27-RUC COMER,
	COALESCE ( T1 . HMMECAC , ' ' ) MOVMCC ,  --28-MCC,
	'000' MOVCANCU ,  --29-CANT CUOTAS,
	T1 . HMCODAU MOVCODAU ,  --31-COD AUTORIZACION,
	T1 . HMIDUSR MOVUSU ,  --32- USU QUE IMPUTO,
	COALESCE ( T8 . MEPIDPROMO , '0' ) MOVPROMO ,  --33-ID PROMO,
	T1 . HMCUPON MOVCUPON ,  --34-COD CUPON,
	CASE
		WHEN T8 . MEPNROCOMP <> ''
			THEN T8 . MEPNROCOMP
		ELSE
			T1 . HMSECUE
	END MOVCOMPG ,  --35-COMPROBANTE PAGO APIS
	'H' MOVTIP --, t1.hmidusr usuario
	FROM GXBDBPS . THMOVAF T1
	INNER JOIN GXBDBPS . TMCTAAF T2 ON T1 . HMNUMCT = T2 . MCNUMCT
	LEFT JOIN GXBDBPS . GCLIEAF T3 ON T2 . MCTIPOD = T3 . CETIPOD AND T2 . MCNUMDO = T3 . CENUMDO AND T1 . HMEMISO = T3 . ENEMISO
	INNER JOIN GXBDBPS . TCMOVAF T4 ON T1 . HMCODIG = T4 . CMCODIG
	LEFT JOIN GXBDBPS . CORUBAF T5 ON SUBSTRING ( T1 . HMCODCO , 1 , 2 ) = T5 . RUCODI
	LEFT JOIN GXBDBPS . COMAEAF T6 ON T1 . HMCODCO = T6 . COCOMER
	LEFT JOIN GXBDBPS . COLOCAF T7 ON T6 . LOCODI = T7 . LOCODI
	LEFT JOIN GXTRJDTA . TMOMEP T8 ON T8 . MEPIDCTA = T1 . HMNUMCT AND T8 . MEPIDMOVCL = T1 . HMCUPON AND T1 . HMCUPON <> 0 AND T8 . MEPFCHPRO = T1 . HMFEPRO
	WHERE T1 . HMCODRE = 0 AND T1 . HMEMISO IN ('021','176') AND T1 . HMFEPRO >= '20230101'
	AND T1 . HMCODIG = '579') --NOT IN ( '123' , '103' , '104' , '124' , '105' , '125' , '106' , '126' , '107' , '127' , '011' ) AND T1 . HMCODIG < '900' ) )
SELECT MOVNREF REFERENCIA, MOVENT ENTIDAD, MOVFECC FECHACOMERCIAL, MOVAFI AFINIDAD, MOVCTA CUENTA, MOVDOC CEDULAIDENTIDAD, LEFT(MOVNUMTA,6)||'XXXXXX'||right(MOVNUMTA,4) TARJETA,
MOVTIPTA TIPOTC, MOVSUC SUCURSALTC, MOVSEX SEXO, MOVCODM CODMOV, MOVDESM DESCRIPMOV, MOVTIPOM TIPOMOV, MOVASALF AFECTASALDOAF, MOVASFNV AFECTSALDOFNV,
MOVSALFI AFECTSALDOFI, MOVACUP AFECTCUOTPEND, MOVACUAP AFECTCUOTAADELPEND, MOVACURP AFECTCUOTAREFPEND, MOVACUMP AFECTACUMPAG, MOVFECR FECHREAL, MOVDIAS DIASEMANA,
MOVIMPO IMPORTE, MOVCODC CODCOMERCIO, MOVDESC DESCCOMER, MOVRUB RUBRO, MOVLOCC LOCALIDAD, MOVRUCC RUCCOMER, MOVMCC MCC, MOVCANCU CANTCUOTAS,
MOVCODAU CODAUTORIZACION, MOVUSU USUARIOIMPUTO, MOVPROMO IDPROMO, MOVCUPON CODCUPON, MOVCOMPG COMPROBANTPAGOAPI, MOVTIP
FROM MOV;