--Tarea: http://redmine2.bepsa.com.py/issues/67302
--Modificación solicitada para la fecha 20231229 como N en campo CALDIAHAB ya está en Producción
--Buenas Fernando como lo conversamos favor ayuda para con el ajuste en la tabla TDSCAL
-- odes darnos una mano y cargar tarea repair para modificar fecha 20231229 como N en campo CALDIAHAB y cargar lo que corresponde a 2024.
SELECT * FROM GXTRJDTA.TDSCAL T;

UPDATE GXTRJDTA.TDSCAL
SET CALDIAHAB='N'
WHERE CALFECHA='20231229';
-------------------------------------------------------
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240101', 1, 2024, 'N', 'Año Nuevo', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240102', 2, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240103', 3, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240104', 4, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240105', 5, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240106', 6, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240107', 7, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240108', 8, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240109', 9, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240110', 10, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240111', 11, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240112', 12, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240113', 13, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240114', 14, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240115', 15, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240116', 16, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240117', 17, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240118', 18, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240119', 19, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240120', 20, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240121', 21, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240122', 22, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240123', 23, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240124', 24, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240125', 25, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240126', 26, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240127', 27, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240128', 28, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240129', 29, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240130', 30, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240131', 31, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240201', 32, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240202', 33, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240203', 34, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240204', 35, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240205', 36, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240206', 37, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240207', 38, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240208', 39, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240209', 40, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240210', 41, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240211', 42, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240212', 43, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240213', 44, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240214', 45, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240215', 46, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240216', 47, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240217', 48, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240218', 49, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240219', 50, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240220', 51, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240221', 52, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240222', 53, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240223', 54, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240224', 55, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240225', 56, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240226', 57, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240227', 58, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240228', 59, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240229', 60, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240301', 61, 2024, 'N', 'Día de los Héroes de la Patria', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240302', 62, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240303', 63, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240304', 64, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240305', 65, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240306', 66, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240307', 67, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240308', 68, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240309', 69, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240310', 70, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240311', 71, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240312', 72, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240313', 73, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240314', 74, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240315', 75, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240316', 76, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240317', 77, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240318', 78, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240319', 79, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240320', 80, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240321', 81, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240322', 82, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240323', 83, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240324', 84, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240325', 85, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240326', 86, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240327', 87, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240328', 88, 2024, 'N', 'Jueves Santo', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240329', 89, 2024, 'N', 'Viernes Santo', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240330', 90, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240331', 91, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240401', 92, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240402', 93, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240403', 94, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240404', 95, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240405', 96, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240406', 97, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240407', 98, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240408', 99, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240409', 100, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240410', 101, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240411', 102, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240412', 103, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240413', 104, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240414', 105, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240415', 106, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240416', 107, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240417', 108, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240418', 109, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240419', 110, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240420', 111, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240421', 112, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240422', 113, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240423', 114, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240424', 115, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240425', 116, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240426', 117, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240427', 118, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240428', 119, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240429', 120, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240430', 121, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240501', 122, 2024, 'N', 'Día de los Trabajadores       ', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240502', 123, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240503', 124, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240504', 125, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240505', 126, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240506', 127, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240507', 128, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240508', 129, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240509', 130, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240510', 131, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240511', 132, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240512', 133, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240513', 134, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240514', 135, 2024, 'N', 'Día de la Independencia', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240515', 136, 2024, 'N', 'Día de la Independencia', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240516', 137, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240517', 138, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240518', 139, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240519', 140, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240520', 141, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240521', 142, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240522', 143, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240523', 144, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240524', 145, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240525', 146, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240526', 147, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240527', 148, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240528', 149, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240529', 150, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240530', 151, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240531', 152, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240601', 153, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240602', 154, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240603', 155, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240604', 156, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240605', 157, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240606', 158, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240607', 159, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240608', 160, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240609', 161, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240610', 162, 2024, 'N', 'Día de la Paz del Chaco       ', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240611', 163, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240612', 164, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240613', 165, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240614', 166, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240615', 167, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240616', 168, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240617', 169, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240618', 170, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240619', 171, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240620', 172, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240621', 173, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240622', 174, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240623', 175, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240624', 176, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240625', 177, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240626', 178, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240627', 179, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240628', 180, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240629', 181, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240630', 182, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240701', 183, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240702', 184, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240703', 185, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240704', 186, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240705', 187, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240706', 188, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240707', 189, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240708', 190, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240709', 191, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240710', 192, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240711', 193, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240712', 194, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240713', 195, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240714', 196, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240715', 197, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240716', 198, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240717', 199, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240718', 200, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240719', 201, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240720', 202, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240721', 203, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240722', 204, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240723', 205, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240724', 206, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240725', 207, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240726', 208, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240727', 209, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240728', 210, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240729', 211, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240730', 212, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240731', 213, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240801', 214, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240802', 215, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240803', 216, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240804', 217, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240805', 218, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240806', 219, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240807', 220, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240808', 221, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240809', 222, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240810', 223, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240811', 224, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240812', 225, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240813', 226, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240814', 227, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240815', 228, 2024, 'N', 'Fundación de Asunción         ', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240816', 229, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240817', 230, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240818', 231, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240819', 232, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240820', 233, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240821', 234, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240822', 235, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240823', 236, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240824', 237, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240825', 238, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240826', 239, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240827', 240, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240828', 241, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240829', 242, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240830', 243, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240831', 244, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240901', 245, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240902', 246, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240903', 247, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240904', 248, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240905', 249, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240906', 250, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240907', 251, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240908', 252, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240909', 253, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240910', 254, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240911', 255, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240912', 256, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240913', 257, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240914', 258, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240915', 259, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240916', 260, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240917', 261, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240918', 262, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240919', 263, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240920', 264, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240921', 265, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240922', 266, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240923', 267, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240924', 268, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240925', 269, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240926', 270, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240927', 271, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240928', 272, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240929', 273, 2024, 'N', 'Batalla de Boquerón           ', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20240930', 274, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241001', 275, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241002', 276, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241003', 277, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241004', 278, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241005', 279, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241006', 280, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241007', 281, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241008', 282, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241009', 283, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241010', 284, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241011', 285, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241012', 286, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241013', 287, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241014', 288, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241015', 289, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241016', 290, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241017', 291, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241018', 292, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241019', 293, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241020', 294, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241021', 295, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241022', 296, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241023', 297, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241024', 298, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241025', 299, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241026', 300, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241027', 301, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241028', 302, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241029', 303, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241030', 304, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241031', 305, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241101', 306, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241102', 307, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241103', 308, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241104', 309, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241105', 310, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241106', 311, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241107', 312, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241108', 313, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241109', 314, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241110', 315, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241111', 316, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241112', 317, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241113', 318, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241114', 319, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241115', 320, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241116', 321, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241117', 322, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241118', 323, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241119', 324, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241120', 325, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241121', 326, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241122', 327, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241123', 328, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241124', 329, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241125', 330, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241126', 331, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241127', 332, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241128', 333, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241129', 334, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241130', 335, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241201', 336, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241202', 337, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241203', 338, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241204', 339, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241205', 340, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241206', 341, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241207', 342, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241208', 343, 2024, 'N', 'Día de la Virgen de Caacupé   ', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241209', 344, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241210', 345, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241211', 346, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241212', 347, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241213', 348, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241214', 349, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241215', 350, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241216', 351, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241217', 352, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241218', 353, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241219', 354, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241220', 355, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241221', 356, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241222', 357, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241223', 358, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241224', 359, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241225', 360, 2024, 'N', 'Navidad                       ', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241226', 361, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241227', 362, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241228', 363, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241229', 364, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241230', 365, 2024, 'S', '', CURRENT USER, CURRENT TIMESTAMP);
INSERT INTO GXTRJDTA.TDSCAL
    (CALFECHA, CALDIAJUL, CALANHO, CALDIAHAB, CALOBSERB, CALUSULTUP, CALFHULTUP)
VALUES ('20241231', 366, 2024, 'N', '', CURRENT USER, CURRENT TIMESTAMP);