SELECT LENEMI EMISOR,ennombr DESCRIP_EMISOR,LCODBC MARCA,LBCOCR,LBCODB,LBINPR BIN,SUBSTR(lnrtar,1,6)||'XXXXXX'||SUBSTR(lnrtar,13,4) TARJETA,LFECTR FECHA_REAL,LFECTR FECHA_COMERCIAL,
LHORTR HORA,LCODTR COD_TRX, TXDTRX DESC_TRX,LNFISC ADQUIRENTE,(case when LNFISC in ('443073','472040') THEN 'BANCARD' when LNFISC = '449780' THEN 'BNF' when LNFISC ='461958' THEN 'AUSTRALIA' 
when LNFISC ='459834' THEN 'MILAN ITALIA' else ' ' END)DESC_ADQUIRENTE,LPOSEM  CODIGO_METODO_ENTRADA,(CASE WHEN LPOSEM in ('9010','9020','910','920') THEN 'BANDA MAGNETICA'  WHEN LPOSEM = '0510' THEN 'CHIP' 
WHEN LPOSEM = '0710' THEN 'CONTACLESS' else 'VACIO' END)MODO_ENTRADA,LMCCTR TIPO_DE_COMERCIO, 
LIDCOM COD_COMERCIO,LCOMTR DENOMINCACION,LIMPGS IMPORTE,SUBSTR(LIDTRA,1,1) DISPOSITIVO,corazo Razon_Social,CORUCN RUC,    
LESTTR ESTADO,LCRETR RESPUESTA,CODDES DESCRIP_RESP,  LCAUTR AUTORIZACION, LERRNB REFERENCIA,AUTPROTAR PRODUCTO,
AUTAMBBIN AMBITO_USO,
AUTTIPTAR TIPO_TARJETA,
(o.OPCOMENT+o.OPCOMBPS) COMISION, (o.OPIVAENT+o.OPIVABPS) IVACOMISION, o.OPRENTA RENTA, o.OPREIVA IVARENTA, (o.OPMONTO-o.OPCOMENT-o.OPCOMBPS-o.OPIVAENT-o.OPIVABPS-o.OPRENTA-o.OPREIVA) NETO, LCUOTA CUOTA,leca62 MODELO_POS

FROM LIBDEBITO.DRCONBEP a
left JOIN GXOPERA.OPMOVI o   ON o.OPNOREF = LERRNB 
INNER JOIN GXBDBPS.TSWAUT j ON lerrnb = j.AUTRRNBEP
inner join gxbdbps.comaeaf  on cocomer =  substr(digits(lidcom), 6, 7)
inner JOIN libdebito.tbcret0p ON lcretr = CODNRO
left join libdebito.tbctra0p on txctrx = lcodtr
LEFT join libdebito.tgembhaf q  on q.crtarj = lnrtar 
LEFT join libdebito.TBINPROC  on PBIN = LBINPR
left JOIN gxbdbps.gentiaf b on b.enemiso = a.lenemi
WHERE LFECTR BETWEEN  '{?DESDE}' AND '{?HASTA}' 
and SUBSTR(LIDTRA,1,1) = '{?DISPOSITIVO}'  --
and LENEMI in ('500','510','540')
and LCODBC = 'VSA'
AND codmar = 'BEPS'

Group by LBINPR,lcodbc,lnrtar,q.crdocu,lfectr,lhortr,lcodtr,TXDTRX,q.crnomb,lmontr,LPOSEM,LMCCTR,LNFACT,LIDTRA,LESTTR,LCRETR,LCAUTR,LNFISC,LCOMTR,LIDCOM,LIMPGS,LENEMI,ennombr,LFCOTR,LERRNB,LBCOCR,LBCODB
,AUTAMBBIN,AUTPROTAR,AUTTIPTAR,OPCOMENT,OPCOMBPS,OPIVAENT,OPIVABPS , OPRENTA, OPREIVA ,OPMONTO,OPCOMENT,CODDES,OPCOMBPS,OPIVAENT,OPIVABPS,OPRENTA,OPREIVA,CORUCN,corazo,LCUOTA,leca62--hAVING COUNT(*) > ,LCUOTA
order by lfectr