--231290010802051--lote anulado para no pagar
--------------------------------------------------------------------------
select mcdisco saldo,  mcnumta tarjeta,   T.* from gxbdbps.tmctaaf T
where MCNUMDO='4179747'; -- mcnumta='6274311550006321';
SELECT * FROM GXBDBPS.TMTARAF T WHERE MTNUMTA in ('6274311460168146','6274311550006321');
SELECT * from gxbdbps.tmctaaf T  where mcnumta in ('6274310212948854','6274311550006321');
----------------------------
----------------------------------------
--query para facturacion
SELECT tmov.movcodcli, tmov.movcodsuc, tmov.movcomer, tmov.movdeno, tmov.MOVTPTA, tmov.MOVESTA,
count(*) CANTIDAD, sum(tmov.movimco) COMISION, sum(tmov.movivco)IVACOMISION, sum(tmov.movimco+tmov.movivco)"COMISION+IVA"
FROM gxfindta.tclmov tmov
   WHERE tmov.movfcre BETWEEN '20250501' AND '20250530'
       AND (tmov.sercodi = 'COMPRA' OR (tmov.sercodi in ('DEBAUT', 'ECOM')
AND tmov.PRECODI in ( 'PREC', 'BTNP') AND tmov.movcodis = 'WEB'
AND tmov.movruc != '80050172-1') OR (tmov.sercodi = 'PUNTOS' AND tmov.PRECODI = 'CAPU'))
and trim(tmov.movruc) != '80016096-7' AND (tmov.movivco + tmov.movimco) <> 0
AND tmov.MOVCODCLI=11612
  GROUP BY tmov.movcodcli, tmov.movcodsuc, tmov.movcomer, tmov.movdeno, tmov.MOVTPTA, tmov.MOVESTA;

Select movcodcli, movcodsuc, movcomer, movdeno, MOVTPTA,count(*) CANTIDAD, sum(movimco) COMISION, sum(movivco)IVACOMISION,
sum(movimco+movivco)"COMISION+IVA" from gxfindta.tclmov where movcodcli = 11612 and sercodi = 'COMPRA' AND movfCRE between '20250501' and '20250530'
group by movcodcli, movcodsuc, movcomer, movdeno, MOVTPTA;
--10937 retail

SELECT /*T.MOVOPDE,*/ T.*
FROM GXFINDTA.TCLMOV T
WHERE T.MOVOPDE = 700405   AND T.SERCODI IN ('VTAMIN', 'PAGFAC')   AND T.MOVFCRE BETWEEN '20250321' AND '20250420';
SELECT *
FROM GXFINDTA.TCLMOV GT
WHERE gT.MOVOPDE = 700405 AND GT.MOVFCRE BETWEEN '20250422' AND '20250521'
    AND (GT.SERCODI IN ('PAGFAC', 'VTAMIN') AND GT.PRECODI IN ('PFEW', 'PFTA', 'VTEP', 'VTEW', 'VTTA')
    AND GT.MOVCODIS IN ('ATM', 'WEB', 'POS')) AND GT.MOVIVCO > 0;

SELECT T.MOVOPDE, T.*
FROM GXFINDTA.TCLMOV T
WHERE T.MOVIDLT='240020096900042';

SELECT * FROM GXFINDTA.TCLTSB T WHERE T.TSBNREF='240740074500189';

SELECT * FROM GXFINDTA.TCMCLI T WHERE T.CLICLICOD=932725;
---para ver si tiene red de pagos
SELECT b.* FROM GXFINDTA.TCMSUC a
JOIN GXFINDTA.TCMSER b
ON a.CLICLICOD = b.CLICLICOD
AND a.SUCSUCCOD = b.SUCSUCCOD
           AND b.SERHABILI='N'
WHERE b.SERCODI = 'REDPAG' AND a.SUCESTADO = 'A' ORDER BY a.CLICLICOD, a.SUCSUCCOD;

SELECT * FROM GXFINDTA.TCOCNA T WHERE T.CLICLICOD IN (3394);
SELECT * FROM GXFINDTA.TCMSER T WHERE T.CLICLICOD IN (3394) AND T.SERCODI='REDPAG';

SELECT * FROM GXBDBPS.COMAEAF C2 WHERE  C2.CORUCN='80025769-3';
SELECT * FROM GXFINDTA.TCMCLI T WHERE T.CLIRUC='80025769-3';
SELECT * FROM GXFINDTA.TCMSUC T WHERE T.CLICLICOD=11447;

SELECT SUM(T.MOVIMPO), T.MOVCOMER
FROM GXFINDTA.TCLMOV T
WHERE T.MOVCOMER IN ('7800046', '7800045', '7800047')
  AND T.MOVFCRE BETWEEN '20240101' AND '20240131'
GROUP BY T.MOVCOMER;

/*Verificaci�n de Facturas Comercios CLaro (No Operadora)*/
SELECT SUBSTR(MOVFCRE, 1, 6)  PERIODO, MOVCODCLI, MOVCODSUC, MOVCOMER, MOVDENO, MOVTPTA,
       COUNT(*)               CANTIDAD, SUM(MOVIMPO)           TOTAL_IMPORTE,
       SUM(MOVIMCO)           COMISION, SUM(MOVIVCO)           IVA_COMISION,
       SUM(MOVIMCO + MOVIVCO) "COMISION+IVA", SUM(MOVNETO)           TOTAL_NETO
FROM GXFINDTA.TCLMOV
WHERE MOVFCRE BETWEEN '20240101' AND '20240131'
--WHERE MOVFPRO >= '20240101'
  AND MOVCODCLI = '11728'
GROUP BY SUBSTR(MOVFCRE, 1, 6), MOVCODCLI, MOVCODSUC, MOVCOMER, MOVDENO, MOVTPTA;

SELECT T.MOVOPDE, T.*
FROM GXFINDTA.TCLMOV T
WHERE-- T.MOVIDLT='240020096900042'
 T.MOVOPDE = 700105
  AND T.SERCODI IN ('VTAMIN', 'PAGFAC')
  AND T.MOVFCRE BETWEEN '20240321' AND '20240420';
--liquidacion operadoras
--('700405' --personal -- , '700105' -- tigo pre-paga -- , '700605' -- claro)
SELECT CASE
           WHEN MOVOPOR = '700405' THEN 'Nucleo'
           WHEN MOVOPOR = '700105' THEN 'Telecel'
           WHEN MOVOPOR = '700605' THEN 'Claro' END,
MOVOPOR OPERADORA, SUM(MOVIMPO) IMPORTE, SUM(MOVIMCO) COMISION, SUM(MOVIVCO) IVA_COMISION,
SUM(MOVIMCO + MOVIVCO) "IVA+COMISION", SUM(MOVNETO) NETO
FROM GXFINDTA.TCLMOV
WHERE MOVOPOR IN ('700405', '700105', '700605')
  AND MOVFCRE BETWEEN '20250621' AND '20250720'
  AND (SERCODI IN ('PAGFAC', 'VTAMIN') AND PRECODI IN ('PFEW', 'PFTA', 'VTEP', 'VTEW', 'VTTA')
    AND MOVCODIS IN ('ATM', 'WEB', 'POS')) --('ATM', 'WEB', 'POS')
  AND MOVIVCO > 0
GROUP BY MOVOPOR;
--facventatotalcomprobml IN (437605.00, 1403777.00)
SELECT *
FROM GXOPERA.OPMOVI O
         INNER JOIN GXFINDTA.TCLMOV T ON T.MOVRRNBEP = O.OPNOREF
         INNER JOIN GXFINDTA.TCLMOD T2 ON T.MOVIDMOV = T2.MOVIDMOV
WHERE O.OPIDTRA = '';

SELECT T.SERCODI, T.MOVCODIS, T.*
FROM GXFINDTA.TCLMOV T
WHERE MOVOPOR = '700405'
  AND T.MOVFPRO = '20250421'
  AND T.SERCODI NOT IN ('COMPRA', 'ADELANTO')
SELECT T.SERCODI, T.MOVCODIS, T.*
FROM GXFINDTA.TCLMOV T WHERE T.MOVRRNBEP in('511176550050','511176236168');

SELECT * FROM GXFINDTA.TCMTIF GT WHERE GT.CLICLICOD=10879;
SELECT * FROM
GXBDBPS.AUTARAF WHERE ATFEREA >='20241014';

SELECT * FROM LIBDEBITO.LINPORTA t WHERE LNUMER='971873921';
--0971873921
--0 985710199
SELECT /*USUCODCAT ID, USUAIDCAT CI, USUCOCOMER COMERCIO, USUNOMCAT NOMBRE, USUESTCAT CATEGORIA,
USUTELCAT TELEFONO, TUSRID TIPOUSUARIO, USUPASSCAT PASS, USUADMCAT CODCAJERO,
USUCORUCCAT RUC, USUCAMBPASCAT NECESITACAMBIARPASS*/ *
FROM GXWEB.USUCAT L
WHERE l.USUTELCAT = '0971873921';
SELECT * FROM GXBDBPS.COMAEAF C2 WHERE C2.COCOMER='4300051';
SELECT * FROM GXBDBPS.COMAEXD C2 WHERE C2.COCOMER='4300051';

SELECT * FROM GXFINDTA.TCLMOV T WHERE T.MOVRRNBEP='419952092097';

    DELETE  FROM VISA.NRT_RRN_EX c where NRTLOGFECH='2024-10-07'
AND NRTLOGHORA BETWEEN '00:14:34' AND  '02:03:33';


    SELECT DATA_QUEUE_LIBRARY, DATA_QUEUE_NAME , MAXIMUM_MESSAGE_LENGTH, CURRENT_MESSAGES
FROM QSYS2.DATA_QUEUE_INFO WHERE DATA_QUEUE_NAME LIKE '%ACFIREC%';

SELECT d.DEPID, d.DEPFECH, d.DEPMONTO, d.DEPFORPAG, d.DEPNROBOL, d.DEPCOM, d.DEPCITIT, d.DEPNOMTITU, d.DEPUSUID, d.DEPUSU,
      d.DEPFECHA, d.DEPHORA, d.DEPESTADO, d.DEPUSUCONF, d.DEPFECHCONF, d.DEPPRODUC, d.DEPBANCO, d.DEPNROASI, d.DEPCTABCO, CLICLICOD, SUCSUCCOD, CNACTAMAD
FROM GXWEB.DEPCICO d
--LEFT JOIN GXFINDTA.TCOCNA tc ON TRIM(d.DEPCOM) = TRIM(tc.COCOMER)
      WHERE d.DEPID = 7982
LEFT JOIN GXFINDTA.TCOCNA tc ON TRIM(d.DEPCOM) = TRIM(tc.COCOMER)
      LIMIT 1;
-------
--query bus d
SELECT CASE WHEN count(*) > 1000 THEN 'ALERT' ELSE 'OK' END AS bus_status2 , count(*) cant2
FROM GXFINDTA.TBDAUV;

SELECT CASE
           WHEN COUNT(*) > 1
               THEN 'MENSAJES ENCOLADOS :'
           ELSE 'TODO OK :)' END AS STATUS,
       COUNT(*)                     CANTIDAD,
       MIN(TRIM(D.OP_AUDFCHT))      PRIMER_MENSAJE_ENCOLADO,
       CURRENT_TIMESTAMP            FECHA_CONTROL
FROM GXFINDTA.TBDAUV D
WHERE D.OP_AUDFCHT < CURRENT_TIMESTAMP - 10 MINUTES
  AND D.OP_AUDFCHT > CURRENT_TIMESTAMP - 1 DAY;

---marcas epin facturación
--setea archvio
UPDATE GXFINDTA.TCLPFD SET PFDVALCHR1 = '14/11/24' WHERE PFCIDPARM = 'CONFIGVISA' AND PFDIDGRUP = 'FECHAEPIN';
---verifica archivos
SELECT T.PFCIDPARM,T.PFDIDGRUP, T.PFDSECU, T.PFDVALCHR1
    FROM GXFINDTA.TCLPFD T
         WHERE T.PFCIDPARM = 'CONFIGVISA' AND T.PFDIDGRUP = 'FECHAEPIN';
---epin visa
select *
from GXFINDTA.TCLPFD
WHERE PFCIDPARM='CONFIGVISA'
AND PFDIDGRUP ='FECHAEPIN';
------------------
--servidor correos
SELECT * FROM GXFINDTA.TCLCNE t WHERE t.CNEIDCON  = 'MAILAS';

---DIF CLEARIN BNF
SELECT * FROM GXOPERA.OPAGO0PH O0P WHERE O0P.PGFCOM='2025-01-02'
AND O0P.PGIDTR IN ('250102724538', '250102724539', '250102724540', '250102724541', '250102724542')
   --AND O0P.PGCMOV=1;
--EL PRIMERO ES COMPRA

SELECT SUM(OPMONTO - OPCOMI)
FROM GXOPERA.OPMOVI O WHERE O.OPFECOM='20250102' AND O.OPENEMI=002 AND O.OPTIPTAR='DEB'
AND O.OPCODTRN='000054' AND OPIDTRA LIKE 'W%';
--AND O.OPSTATUS='E' --REVERSA
--AND O.OPMONTO-O.OPCOMI='15492'; SUMA PARA VER SI ENCUENTRO
SELECT *--SUM(T.MOVNETO)
FROM GXFINDTA.TCLMOV T WHERE T.MOVFPRO='20250102' AND T.SERCODI='COMPRA' AND T.MOVCODEM='100201'
AND T.MOVCDBCC IN (104004,900004)
                         AND T.MOVTPTA='D'
AND T.MOVMARC='DIN';

SELECT * FROM GXBDBPS.COMAEAF C2 WHERE C2.COCOMER IN ('6901787', '6902029');

select 'BATCH' origen,'01-COMPRA' agrupador,/*sum(opmonto) Bruto,*/
    sum(opmonto-opcomi) "01-Neto" ,sum(opcoment)  "02-COMI_BANCO",sum(opcombps) "03-COMI_PROCESADORA",
    sum(opivaent) "04-IVA_BANCO",sum(opivabps) "05-IVA_BEPSA" , licodban, litipago
from gxopera.opmovi
inner join gxopera.flicom b on opcomer = licomer and opfecom = lifechd and opcodtrn= licodtr
where opliqde ='20250102' and OPENTID = '002' and OPTIPTAR = 'DEB' and OPCODTRN ='000054'
--and licodban NOT IN ('01','BB','BC','CO','AT','BA', 'IF', 'EC', 'BN','BS','IB');

GROUP BY  b.LICODBAN, b.LITIPAGO;

SELECT T.MOVFPRO, T.MOVRRNBEP, T.MOVCOMER, T.MOVDENO, T.MOVCODEM, T.MOVDESEM, T.SERCODI, T.MOVCODIS, T.MOVIMPO,
       (O.OPMONTO-O.OPCOMI) NETO
FROM GXFINDTA.TCLMOV T
INNER JOIN gxopera.opmovi O ON T.MOVRRNBEP = O.OPNOREF
         WHERE T.MOVRRNBEP IN ('436628191143', '500229060200', '436628267410', '436628127482', '500228855340');

SELECT  * FROM GXFINDTA.TCLTSB T WHERE T.TSBNREF IN ('250360015700169');
SELECT * FROM GXFINDTA.TCLTSB T WHERE T.TSBCOCO='8621245' AND T.TSBFPRO >='20250201';
SELECT T.MOVCOMER, T.* FROM GXFINDTA.TCLMOV T WHERE T.MOVRRNBEP IN ('503644299416','503644290532');

SELECT SUM(T.MOVNETO) FROM GXFINDTA.TCLMOV T WHERE T.MOVIDLT='250360015700169';
select * from GXFINDTA.TCLIMB where SUBSTR(IMBIDOP, 9 , 7)= 5700169 AND IMBFCH>='20250201';
SELECT * FROM GXOPERA.OPLIQUI O WHERE O.OPNROREF IN ('503644299416','503644290532');

SELECT * FROM GXFINDTA.TCLIMB T WHERE IMBFCH ='20250205' AND T.IMBSER='PAGOCOM'; --AND
SELECT * FROM GXFINDTA.TCLRTC T WHERE T.RTCCOMERC='5700169';
SELECT * FROM GXFINDTA.TCLRTD T WHERE RTCIDRETEN='1100444';
---------------------------------------------------------
SELECT T.MOVOPOR , SUM(T.MOVNETO), T.SERCODI FROM GXFINDTA.TCLMOV T WHERE MOVFECLIQ = '20250203' AND T.MOVFPRO<>'20250203'
GROUP BY T.MOVOPOR, T.SERCODI;

SELECT T.MOVOPOR , SUM(T.MOVNETO), T.SERCODI, T.MOVFPRO FROM GXFINDTA.TCLMOV T WHERE MOVFECLIQ = '20250203'
AND T.SERCODI='VTAMIN'--AND T.MOVFPRO<>'20250203'
GROUP BY T.MOVOPOR, T.SERCODI, T.MOVFPRO;

SELECT * FROM GXFINDTA.TCLTSB T WHERE T.TSBCOCO='0705719' ORDER BY TSBFEGE DESC;

select C.AFTIDESC DESCRIPCION, AFFALTA FECHAALTA, AFFINST FECHAINSTAL, afcodi activo, AFSERN NROSERIAL,
(case when AFSTAT = '00' then 'ACTIVO' WHEN AFSTAT = '50' THEN 'MANTENIMIENTO' when AFSTAT = '60' then 'DEPOSITO'
WHEN AFSTAT = '90' then 'BAJA' WHEN AFSTAT = '01' then 'PENDIENTE DE ACTIVACION' end) estado
from  GXBDBPS.COMAEAF A
INNER JOIN gxbdbps.COAFMAF B ON (AFCOMER = COCOMER)
INNER JOIN GXBDBPS.COAFTAF  C ON  B.AFTICODI = C.AFTICODI
/*WHERE COSTAT <> '90'
--AND SUBSTR(COCOMER,1,2) NOT IN ('90', '95', '99')
and cocomer <> '0100001'*/;
;

SELECT F2.cocomer, F2.CORAZO, m2.afcodi, m2.affmodi as fecha_mod, m2.afidusal user_alta, m2.afidusmd as user_modf, M2.*
FROM GXBDBPS.COMAEAF F2,
     GXBDBPS.COAFMAF M2
WHERE M2.AFCOMER = F2.COCOMER  AND M2.afidusmd in ('OPTKDOSB','OGPKDOSB') AND M2.affmodi >='20250601';

/*Activo Fijo*/
SELECT afcodi activo_fijo, b.* FROM gxbdbps.coafmaf b  WHERE afcodi = '24848427'; --legacy
SELECT disactcod activo_fijo, a.* FROM gxfindta.tcmdis a  WHERE disactcod = '24848427' ; --ri
SELECT * FROM gxfindta.tcocna WHERE cliclicod = 29659;