SELECT ENTRY_TIMESTAMP AS ENTRY,
JOURNAL_CODE AS JRNCODE,
CASE WHEN JOURNAL_ENTRY_TYPE = 'PT'
THEN 'INSERT'
WHEN JOURNAL_ENTRY_TYPE = 'PX'
THEN 'INSERT BY RRN'
WHEN JOURNAL_ENTRY_TYPE = 'UB'
THEN 'UPDATE BEFORE'
WHEN JOURNAL_ENTRY_TYPE = 'UP'
THEN 'UPDATE AFTER'
WHEN JOURNAL_ENTRY_TYPE = 'DL'
THEN 'DELETE'
ELSE JOURNAL_ENTRY_TYPE
END AS JRNTYPE,
JOB_NAME AS JOBNAME, JOB_USER AS JOBUSER,JOB_NUMBER AS JOBNBR,SUBSTR(OBJECT,1,10) AS FILE,
SUBSTR(OBJECT,11,10) AS FILELIB, SUBSTR(OBJECT,21,10) AS FILEMBR,OBJECT_TYPE AS OBJTYPE,
PROGRAM_NAME AS PGMNAME,PROGRAM_LIBRARY AS PGMLIB,CAST(ENTRY_DATA AS CHAR(2000)) AS RECORD,
SEQUENCE_NUMBER AS SEQNBR FROM TABLE(DISPLAY_JOURNAL('@JOURNAL',
'QSQJRN', JOURNAL_CODES => 'R', OBJECT_LIBRARY => 'WRKADOLFO', OBJECT_NAME => 'TSWAUT',
OBJECT_MEMBER => 'TSWAUT', OBJECT_OBJTYPE => '*FILE'))
AS X
/*WHERE SUBSTR(CHAR(ENTRY_TIMESTAMP),1,10) =
''' || &CHECK_DATE || '''*/
ORDER BY SEQUENCE_NUMBER;

SELECT * FROM WRKADOLFO.TSWAUT T;

SELECT ENTRY_TIMESTAMP as JE_TIME, CURRENT_USER as CURRENT_USR,
SEQUENCE_NUMBER, JOURNAL_ENTRY_TYPE,JOB_NAME,
JOB_USER, JOB_NUMBER,PROGRAM_NAME,
OBJECT,OBJECT_TYPE,PATH_NAME,
CAST(cast(substring(entry_data, 1, 32) as char(32) for bit data) as CHAR(32) CCSID 1141) as F1,
CAST(cast(substring(entry_data, 33, 130) as char(130) for bit data) as CHAR(130) CCSID 1141) as F2,
HEX(cast(substring(entry_data, 163, 258) as char(258) for bit data)) as F3,
HEX(cast(substring(entry_data, 421, 6) as char(6) for bit data)) as N1,
HEX(cast(substring(entry_data, 427, 11) as char(11) for bit data)) as N2,
HEX(cast(substring(entry_data, 438, 4) as char(4) for bit data)) as N3
FROM TABLE(DISPLAY_JOURNAL('@JOURNAL',
'QSQJRN',
JOURNAL_CODES => 'R',
OBJECT_LIBRARY => 'MASTERCARD',
OBJECT_NAME => 'MASCTLDTA',
OBJECT_MEMBER => 'MASCTLDTA',
OBJECT_OBJTYPE => '*FILE'))
ORDER BY ENTRY_TIMESTAMP asc;

---ver
--https://stackoverflow.com/questions/78132931/using-sql-to-view-as400-journal-data-entry-data-in-particular
SELECT
-- general Info
ENTRY_TIMESTAMP, SEQUENCE_NUMBER, RECEIVER_LIBRARY, RECEIVER_NAME, journal_code, journal_entry_type, COUNT_OR_RRN,
"CURRENT_USER" AS User, (JOB_NUMBER CONCAT '/' CONCAT TRIM(JOB_USER) CONCAT '/' CONCAT JOB_NAME) as JOB,
PROGRAM_NAME, PROGRAM_LIBRARY, REFERENTIAL_CONSTRAINT, TRIGGER,
-- entry_data = ESD = Field data
INTERPRET(substring(entry_data, 1, 32) as CHAR(32) CCSID 1141) as F1, -- char
INTERPRET(substring(entry_data, 33, 130) as VARCHAR(128) CCSID 1141) as F2, -- varchar
INTERPRET(substring(entry_data, 163, 258) as NVARCHAR(128)) as F3, -- nvarchar
INTERPRET(substring(entry_data, 421, 6) as DECIMAL(11,2) ) as N1, -- decimal
INTERPRET(substring(entry_data, 427, 11) as NUMERIC(11,2) ) as N2, -- numeric
INTERPRET(substring(entry_data, 438, 4) as INTEGER) as N3 -- int
FROM TABLE (
                 QSYS2.DISPLAY_JOURNAL( '@JOURNAL', 'QSQJRN', OBJECT_NAME=>'MASCTLDTA',
                 STARTING_RECEIVER_NAME => '*CURAVLCHN',
                 OBJECT_LIBRARY=>'MYDB',
                 OBJECT_OBJTYPE=>'*FILE',
                 OBJECT_MEMBER=>'*ALL',
                 JOURNAL_ENTRY_TYPES =>'*RCD')) AS JT
where INTERPRET(substring(entry_data, 1, 32) as CHAR(32) CCSID 1141) = 'A'; -- filtering for F1 data