SHOW FULL PROCESSLIST;
/*En la columna "State" tiene que decir = "Locked" si está bloqueado y en la columna "Info" muestra la query que está ejecutando-.*/
SELECT * FROM information_schema.processlist;/*--Esto muestra casi lo mismo...*/
SHOW INDEX FROM k2b_prod.asientocontable; /*--muestra los índices creados sobre la tabla que quieras consultar...*/
--
SHOW ENGINE INNODB STATUS;
--
select now();/*ver la hora de la db*/
SET global general_log = 1; /*activar log*/
SELECT version(); -- ver version mysql
#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*Sentencia para actualización de fechas de Activo Fijo K2B*/
UPDATE bienactivofijo SET bienactivofijofechaactivacion = bienactivofijofechaadquisicion WHERE bienactivofijofechaadquisicion >= '2021-01-01' AND bienactivofijofechaadquisicion > bienactivofijofechaactivacion;
/*k2b cambio de estado para email*/
SELECT WFPrcId, WFTaskCod, WFTaskName, WFTaskDsc, WFTaskEMail from wftask where WFPrcId =5 AND WFTaskCod=22;
UPDATE wftask SET WFTaskEMail ='Y' WHERE WFPrcId =5 AND WFTaskCod=22;
#---------------------------------------------------------------------------------------------------------------
SELECT * FROM BIENACTIVOFIJO WHERE BienActivoFijoId='2761';
select * from producto where ProductoId = 3642;
SELECT * FROM CENTROALMACENAJE WHERE CENTROALMACENAJEID='16';
SELECT * FROM IMPBEPSAOTTIPOCONEXION;
select * from deposito where CentroAlmacenajeId = 16;
SELECT * FROM IMPBEPSAOTMARCADISPOSITIVO;
/*---k2b*/
select WFTaskEMail, WFTaskName, WFPrcId from wftask where WFTaskEMail = 'Y';
select * from wftask where WFTaskName like '%Orden de Compra%';
/*----------------------*/
select * from cliente where ClienteCodigo='14655-6';
select * from persona where PersonaDocumento='1005399-9';
/*----UPDATE para corregir configuración módulo de planificación K2B*/
update ItemAfectacionAfectable set itemafectablemodoafectacion = 'DIRECTO' where itemafectablemodoafectacion = 'INDIRECTO'
and tipoafectacioncodigo = 'PRESUPUESTAL'; UPDATE ItemCostoRestriccion SET itemcostorestitemafectablemodo = 'DIRECTO'
where itemcostorestitemafectablemodo = 'INDIRECTO' and itemcostoresttipoafectacioncod = 'PRESUPUESTAL';
/*--Actualización de datos de proveedores en el ambiente producción de K2B*/
INSERT INTO `k2b_prod`.`imppytimbradoproveedor`
    (`ImpPYTimbradoProvID`,
    `ImpPYTimbradoK2BProveedorID`,
    `ImpPYTimbradoProvCodTimb`,
    `ImpPYTimbradoProvSuc`,  `ImpPYTimbradoProvPuntoExped`,
    `ImpPYTimbradoProvFechaDesde`,
    `ImpPYTimbradoProvFechaHasta`
    )
    VALUES (2,20546,15662555,'001','001','2021-12-31','2022-12-31');
--
INSERT INTO `k2b_prod`.`imppytimbradoproveedortiposdoc`
    (`ImpPYTimbradoProvID`,
    `ImpPYTimbradoK2BProveedorID`,
    `ImpPYTipoDocSETCodigo`,
    `ImpPYTimbradoComprHasta`,
    `ImpPyTimbradoComprDesde`
    )
    VALUES(762,2007,'1','1','1000000');
/*realizamos un cambio con el proveedor Repair-SMD #43969*/
update itemafectacionafectable set ItemAfectablePresupuestoHabili = 1 where ItemAfectablePresupuestoHabili = 0 and TipoAfectacionCodigo = 'PRESUPUESTAL';
/*para validar una solución a un error de POS*/
select * FROM MOVIMIENTOSTOCK m, MOVIMIENTOSTOCKDETALLE d, MOVIMIENTOSTOCKINVENTARIO mi
where mi.MovStockId = d.MovStockId
and mi.MovStockDetId = d.MovStockDetId
and d.MovStockId = m.MovStockId
and MovStockEstadoProcesoIngreso = 'NoCompletado';
/*--Habilitacion de notificaciones por correo: solicitudes de fondos*/
SELECT WFPrcId, WFTaskCod, WFTaskName, WFTaskDsc, WFTaskEMail from wftask where WFPrcId =5 AND WFTaskCod=22;
UPDATE wftask SET WFTaskEMail ='Y' WHERE WFPrcId =5 AND WFTaskCod=22;
--
SELECT WFPrcId, WFTaskCod, WFTaskName, WFTaskDsc, WFTaskEMail from wftask where WFPrcId =47 AND WFTaskCod IN (22,29,184,204);
UPDATE wftask SET WFTaskEMail ='Y' where WFPrcId =47 AND WFTaskCod IN (22,29,184,204);
/*---Sentencia para actualización de fechas de Activo Fijo K2B*/
UPDATE bienactivofijo SET bienactivofijofechaactivacion = bienactivofijofechaadquisicion WHERE bienactivofijofechaadquisicion >= '2021-01-01' AND bienactivofijofechaadquisicion > bienactivofijofechaactivacion;
/*---Con referencia al problema con el deposito Lo que se debe hacer para solucionar esto es modificar por BD el tipo de depósito*/
UPDATE deposito SET tipodepositocodigo = 'TRANSITO' WHERE depositoid = 56 AND depositonombre LIKE 'Transito%';
/*Y  lo que me pidieron recalcar es : El depósito de tipo Transito sirve para mostrar que el material está en viaje desde CA origen a uno de destino. No se debe permitir cambiar el tipo o eliminar depósitos en Tránsito
Todos los CA deben tener un solo depósito de tipo Tránsito.*/
/*-------------------------------------------------------------------------------------------*/
/*Con este cambio la misma dejará de reservar stock cada vez que se realice un movimiento utilizando la misma.*/
/*1.*/	update tipotransaccionstock set tipotrnstktipostkreservacodigo = null  where tipotrnstkcodigo ='TRANSFERENCIA';
/*2.*/	update tipotransaccionstock set TipoTrnStkReserva = 0 where tipotrnstkcodigo ='TRANSFERENCIA';
/*-------------------------------------------------------------------------------------------*/
SET GLOBAL general_log = 1;
SET GLOBAL LOG_OUTPUT = 'TABLE';
set global slow_query_log = 'ON';

SELECT * FROM CLIENTE C;

SELECT * FROM MYSQL.GENERAL_LOG GL;
TRUNCATE MYSQL.GENERAL_LOG;

SELECT * FROM information_schema.triggers;
#----
SELECT * FROM k2b_prod.USUARIO U;
SELECT * FROM ASIENTOCONTABLE WHERE ASIENTONUMERO='32481' AND ASIENTOFECHA='20230619' #AND ASIENTOESTADO='INI'
AND TipoAsientoCodigo='POSCLEARPAGDINEBCONT';

SELECT * FROM ASIENTOCONTABLE A WHERE A.ASIENTONUMERO='51625';
SELECT * FROM NUMERADOR N;

SELECT ASIENTOESTADO, ASIENTOESTADOPROCESO, TIPOASIENTOCODIGO FROM ASIENTOCONTABLE A WHERE ASIENTOFECHA>='20230801'
GROUP BY ASIENTOESTADO, ASIENTOESTADOPROCESO, TIPOASIENTOCODIGO;

SELECT * FROM TIPOASIENTOCONTABLE T;
SELECT * FROM TIPOASIENTOCONTABLEDETALLE T;
SELECT * FROM TIPOASIENTOCONTABLEDETALLEPE T;
/*tipo de documento*/
SELECT * FROM TIPODOCUMENTO T WHERE TIPODOCUMENTOID='32';
SELECT * FROM NUMERADOR N WHERE NUMERADORCODIGO='ASIENTOCODIGO';
SELECT `NumeradorNivelId`, `NumeradorSerieEstado`, `NumeradorCodigo`, `SerieId`, `NumeradorSecuencialVigenciaId`
FROM `NumeradorSecuenciaNexo` WHERE (`NumeradorCodigo` = 'AsientoCodigo                           ')
AND (`NumeradorNivelId` IS NULL) AND (`NumeradorSerieEstado` = 'Activo') ORDER BY `NumeradorCodigo`;
SELECT * FROM `Numerador` WHERE (`NumeradorCodigo` = 'AsientoCodigo                           ')
AND (Not (LENGTH(TRIM(`NumeradorCalificador1`))=0)) ORDER BY `NumeradorCodigo`  LIMIT 1;
#---------------------#
SELECT T1.`ASIENTOID`,
       T2.`TIPOASIENTOCODIGO`              AS TIPOASIENTOCODIGO,
       T2.`ASIENTOESTADO`,
       T5.`TIPODOCUMENTOID`,
       T3.`TIPOTRANSACCIONMODOEJECUCIONBA` AS TIPOASIENTOMODOEJECUCIONBATCHC,
       T1.`ITEMPROYECTOID`,
       T1.`CENTROINGRESOID`,
       T1.`CENTROCOSTOID`,
       T1.`ASIENTODETVTOFINANCIERODOCUMEN`,
       T1.`MONEDACODIGO`,
       T1.`CUENTAAUXCONTABLEID`,
       T1.`CUENTACONTABLEID`,
       T2.`ASIENTOEMPID`,
       T2.`ASIENTOFECHA`,
       T1.`CRITERIOCONTABLECODIGO`,
       T1.`ASIENTODETIMPCALMONEDACONSOLID`,
       T1.`ASIENTODETIMPCALMONEDAEXTRANJE`,
       T1.`ASIENTODETIMPCALMONEDALOCAL`,
       T1.`ASIENTODETIMPCALMONEDAORIGEN`,
       T1.`ASIENTODETTIPODOCUMENTOID`      AS ASIENTODETTIPODOCUMENTOID,
       T4.`ENTIDADCODIGO`                  AS ASIENTODETENTIDADCODIGO,
       T1.`ASIENTODETDOCUMENTOID`,
       T1.`ASIENTODETDOCUMENTOCODIGOEXTER`,
       T4.`TIPODOCUMENTOINTERNOK2B`        AS ASIENTODETTIPODOCUMENTOINTERNO,
       T1.`ASIENTODETID`
FROM ((((`ASIENTOCONTABLEDETALLE` T1 INNER JOIN `ASIENTOCONTABLE` T2 ON T2.`ASIENTOID` = T1.`ASIENTOID`) INNER JOIN `TIPOTRANSACCION` T3 ON T3.`TIPOTRANSACCIONCODIGO` = T2.`TIPOASIENTOCODIGO`) LEFT JOIN `TIPODOCUMENTO` T4 ON T4.`TIPODOCUMENTOID` = T1.`ASIENTODETTIPODOCUMENTOID`) LEFT JOIN `CUENTACONTABLETIPODOCUMENTONEX` T5 ON T5.`CUENTACONTABLEID` = T1.`CUENTACONTABLEID` AND T5.`TIPODOCUMENTOID` = T1.`ASIENTODETTIPODOCUMENTOID`)
WHERE (T2.`ASIENTOFECHA` >= '1000-01-01')
  AND (T2.`ASIENTOFECHA` <= '2023-07-31')
  AND (T2.`ASIENTOESTADO` = 'ACT')
  AND (T2.`ASIENTOEMPID` = 1)
  AND (T1.`CUENTACONTABLEID` = 3)
  AND (T1.`CUENTAAUXCONTABLEID` = 25)
  AND (T3.`TIPOTRANSACCIONMODOEJECUCIONBA` <> 'Apertura')
  AND (T3.`TIPOTRANSACCIONMODOEJECUCIONBA` <> 'Cierre');
SELECT T1.`ITEMPROYECTOID`,
       T1.`CUENTACONTABLEID`,
       T6.`ASIENTOEMPID`,
       T1.`CRITERIOCONTABLECODIGO`,
       T6.`ASIENTOESTADO`,
       T7.`TIPOTRANSACCIONMODOEJECUCIONBA` AS TIPOASIENTOMODOEJECUCIONBATCHC,
       T6.`ASIENTOFECHA`,
       T1.`CUENTAAUXCONTABLEID`,
       T1.`MONEDACODIGO`,
       T3.`CUENTACONTABLESALDOPORPROYECTO`,
       T5.`TIPODOCUMENTOCODIGO`            AS ASIENTODETTIPODOCUMENTOCODIGO,
       T8.`TIPODOCUMENTOCODIGO`            AS ASIENTOTIPODOCUMENTOCODIGO,
       T1.`ASIENTODETOBSERVACIONES`,
       T6.`ASIENTOOBSERVACIONES`,
       T7.`TIPOTRANSACCIONNOMBRE`          AS TIPOASIENTODESCRIPCION,
       T1.`ASIENTODETVTOFINANCIERODOCUMEN`,
       T1.`ASIENTODETFECHAVALOR`,
       T2.`ITEMPROYECTONOMBRE`,
       T4.`MONEDASIMBOLO`,
       T1.`ASIENTODETIMPCALMONEDAORIGEN`,
       T6.`ASIENTONUMERO`,
       T6.`TIPOASIENTOCODIGO`              AS TIPOASIENTOCODIGO,
       T6.`ASIENTOTIPODOCUMENTOID`         AS ASIENTOTIPODOCUMENTOID,
       T8.`ENTIDADCODIGO`                  AS ASIENTOENTIDADCODIGO,
       T6.`ASIENTODOCUMENTOID`,
       T6.`ASIENTODOCUMENTOCODIGOEXTERNO`,
       T8.`TIPODOCUMENTOINTERNOK2B`        AS ASIENTOTIPODOCUMENTOINTERNOK2B,
       T1.`ASIENTODETTIPODOCUMENTOID`      AS ASIENTODETTIPODOCUMENTOID,
       T5.`ENTIDADCODIGO`                  AS ASIENTODETENTIDADCODIGO,
       T1.`ASIENTODETDOCUMENTOID`,
       T1.`ASIENTODETDOCUMENTOCODIGOEXTER`,
       T5.`TIPODOCUMENTOINTERNOK2B`        AS ASIENTODETTIPODOCUMENTOINTERNO,
       T1.`ASIENTODETIMPORTEMONEDACONSOLI`,
       T1.`ASIENTODETIMPORTEMONEDAEXTRANJ`,
       T1.`ASIENTODETTIPOMOVIMIENTO`,
       T1.`ASIENTODETIMPORTEMONEDALOCAL`,
       T6.`ASIENTOEXTORNO`,
       T1.`ASIENTOID`,
       T1.`ASIENTODETID`
FROM (((((((`ASIENTOCONTABLEDETALLE` T1 LEFT JOIN `ITEMPROYECTO` T2 ON T2.`ITEMPROYECTOID` = T1.`ITEMPROYECTOID`) INNER JOIN `CUENTACONTABLECRITERIONEXO` T3 ON T3.`CUENTACONTABLEID` = T1.`CUENTACONTABLEID` AND T3.`CRITERIOCONTABLECODIGO` = T1.`CRITERIOCONTABLECODIGO`) INNER JOIN `MONEDA` T4 ON T4.`MONEDACODIGO` = T1.`MONEDACODIGO`) LEFT JOIN `TIPODOCUMENTO` T5 ON T5.`TIPODOCUMENTOID` = T1.`ASIENTODETTIPODOCUMENTOID`) INNER JOIN `ASIENTOCONTABLE` T6
        ON T6.`ASIENTOID` = T1.`ASIENTOID`) INNER JOIN `TIPOTRANSACCION` T7 ON T7.`TIPOTRANSACCIONCODIGO` = T6.`TIPOASIENTOCODIGO`) LEFT JOIN `TIPODOCUMENTO` T8 ON T8.`TIPODOCUMENTOID` = T6.`ASIENTOTIPODOCUMENTOID`)
WHERE (T1.`CUENTACONTABLEID` = 3)
  AND (T6.`ASIENTOEMPID` = 1)
  AND (T1.`CRITERIOCONTABLECODIGO` = 'DEV')
  AND (T6.`ASIENTOESTADO` = 'ACT')
  AND (T1.`CUENTAAUXCONTABLEID` = 25)
  AND (T6.`ASIENTOFECHA` >= '2023-08-01')
  AND (T6.`ASIENTOFECHA` <= '2023-08-01')
  AND (T7.`TIPOTRANSACCIONMODOEJECUCIONBA` <> 'Apertura')
  AND (T7.`TIPOTRANSACCIONMODOEJECUCIONBA` <> 'Cierre')
ORDER BY T6.`ASIENTOFECHA`, T6.`TIPOASIENTOCODIGO`, T6.`ASIENTONUMERO`;
SELECT T1.`ASIENTOID`,
       T2.`TIPOASIENTOCODIGO`              AS TIPOASIENTOCODIGO,
       T2.`ASIENTOESTADO`,
       T5.`TIPODOCUMENTOID`,
       T3.`TIPOTRANSACCIONMODOEJECUCIONBA` AS TIPOASIENTOMODOEJECUCIONBATCHC,
       T1.`ITEMPROYECTOID`,
       T1.`CENTROINGRESOID`,
       T1.`CENTROCOSTOID`,
       T1.`ASIENTODETVTOFINANCIERODOCUMEN`,
       T1.`MONEDACODIGO`,
       T1.`CUENTAAUXCONTABLEID`,
       T1.`CUENTACONTABLEID`,
       T2.`ASIENTOEMPID`,
       T2.`ASIENTOFECHA`,
       T1.`CRITERIOCONTABLECODIGO`,
       T1.`ASIENTODETIMPCALMONEDACONSOLID`,
       T1.`ASIENTODETIMPCALMONEDAEXTRANJE`,
       T1.`ASIENTODETIMPCALMONEDALOCAL`,
       T1.`ASIENTODETIMPCALMONEDAORIGEN`,
       T1.`ASIENTODETTIPODOCUMENTOID`      AS ASIENTODETTIPODOCUMENTOID,
       T4.`ENTIDADCODIGO`                  AS ASIENTODETENTIDADCODIGO,
       T1.`ASIENTODETDOCUMENTOID`,
       T1.`ASIENTODETDOCUMENTOCODIGOEXTER`,
       T4.`TIPODOCUMENTOINTERNOK2B`        AS ASIENTODETTIPODOCUMENTOINTERNO,
       T1.`ASIENTODETID`
FROM ((((`ASIENTOCONTABLEDETALLE` T1 INNER JOIN `ASIENTOCONTABLE` T2 ON T2.`ASIENTOID` = T1.`ASIENTOID`) INNER JOIN `TIPOTRANSACCION` T3 ON T3.`TIPOTRANSACCIONCODIGO` = T2.`TIPOASIENTOCODIGO`) LEFT JOIN `TIPODOCUMENTO` T4 ON T4.`TIPODOCUMENTOID` = T1.`ASIENTODETTIPODOCUMENTOID`) LEFT JOIN `CUENTACONTABLETIPODOCUMENTONEX` T5 ON T5.`CUENTACONTABLEID` = T1.`CUENTACONTABLEID` AND T5.`TIPODOCUMENTOID` = T1.`ASIENTODETTIPODOCUMENTOID`)
WHERE (T2.`ASIENTOFECHA` >= '1000-01-01')
  AND (T2.`ASIENTOFECHA` <= '2023-07-31')
  AND (T2.`ASIENTOESTADO` = 'ACT')
  AND (T2.`ASIENTOEMPID` = 1)
  AND (T1.`CUENTACONTABLEID` = 3)
  AND (T1.`CUENTAAUXCONTABLEID` = 25)
  AND (T3.`TIPOTRANSACCIONMODOEJECUCIONBA` <> 'Apertura')
  AND (T3.`TIPOTRANSACCIONMODOEJECUCIONBA` <> 'Cierre');

SELECT * FROM k2b_prod.DOCUMENTOCOMERCIAL D WHERE D.DOCCOMCODIGO='001-001-0225404';
SELECT * FROM k2b_prod.DOCUMENTOCOMERCIALDETALLE D WHERE D.DOCCOMID=14349;
#PARA PLANIFICACIÓN
SELECT * FROM k2b_prod.CONFORMACIONCOMERCIAL C WHERE C.CONFCOMID='10037';

SELECT * FROM k2b_prod.PEDIDOCOMPRAAUTORIZACION P WHERE P.PEDIDOCMPID='1055';
SELECT * FROM k2b_prod.BIENACTIVOFIJO B WHERE B.BienActivoFijoMarca='SPECTRA';

SELECT * FROM k2b_prod.CLIENTE C WHERE C.CLIENTECODIGO=18055-1;
SELECT * FROM k2b_prod.PERSONAJURIDICA P WHERE PersonaJuridicaNombreLegal='CONCEPCION BEATRIZ VELAZQUEZ OSORIO';
SELECT * FROM k2b_prod.PERSONA P WHERE PersonaNombre LIKE '%BEATRIZ VELAZQUEZ%';#'DIOSNEL DELVALLE FERNANDEZ';

SELECT * FROM k2b_prod.ASIENTOCONTABLE A WHERE A.ASIENTONUMERO IN ('51620','51626','51632','51637');
SELECT * FROM k2b_prod.ASIENTOCONTABLEDETALLE A WHERE A.ASIENTOID IN ('59417','59423','59429','59434');
#---------------------------------------------#
SELECT * FROM k2b_prod.ASIENTOCONTABLE A WHERE A.ASIENTONUMERO IN ('54428','54432');
SELECT * FROM k2b_prod.ASIENTOCONTABLEDETALLE A WHERE A.ASIENTOID IN ('62416','62422');
#--------------------------------------
SELECT * FROM ASIENTOCONTABLE A WHERE A.ASIENTONUMERO='54064';
SELECT * FROM CUENTACONTABLE C WHERE C.CUENTACONTABLECODIGO='5.1.1.2.1';

SELECT * FROM CUENTACONTABLE C WHERE C.CUENTACONTABLECODIGO LIKE '5.1.1.2.1.%';

SELECT T1.`ASIENTOID`,
       T2.ASIENTONUMERO,
       T2.`ASIENTOESTADO`,
       T2.`ASIENTOFECHA`,
       T2.`ASIENTOPERIODOCIERREID`,
       T1.`CUENTACONTABLEID`,
       T1.`ASIENTODETIMPCALMONEDALOCAL`,
       T1.`ASIENTODETIMPCALMONEDAEXTRANJE`,
       T1.`ASIENTODETIMPCALMONEDACONSOLID`,
       T1.`ASIENTODETID`
FROM (k2b_preprod.`ASIENTOCONTABLEDETALLE` T1 INNER JOIN k2b_preprod.`ASIENTOCONTABLE` T2 ON T2.`ASIENTOID` = T1.`ASIENTOID`)
WHERE (T1.`CUENTACONTABLEID` = 720)
  AND (T2.`ASIENTOFECHA` >= '2023-08-01')
  AND (T2.`ASIENTOFECHA` <= '2023-08-31')
  AND (T2.`ASIENTOPERIODOCIERREID` = 211)
  AND (T2.`ASIENTOESTADO` = 'ACT')
ORDER BY T1.`CUENTACONTABLEID`;

SELECT * FROM k2b_preprod.EJERCICIOCONTABLE E;
SELECT * FROM k2b_preprod.EJERCICIOCONTABLEPERIODOCIERRE E;

SELECT * FROM K2B_PREPROD.ASIENTOCONTABLE T WHERE T.ASIENTONUMERO/*AsientoUsuarioCodigo IN ('JENCISO','KDOSBUSER') AND T.ASIENTOFECHA >='2023-08-01'*/
IN('51624','51625','51630','51635','51583');

SELECT * FROM K2B_PREPROD.ASIENTOCONTABLEDETALLE A WHERE A.ASIENTOID='59427';

SELECT * FROM k2b_prod.ASIENTOCONTABLE A WHERE A.ASIENTONUMERO='51624'; /*DESC 216 A 211*/
SELECT * FROM k2b_prod.ASIENTOCONTABLE A WHERE A.ASIENTONUMERO='51625'; /*DESC 216 A 211*/
SELECT * FROM k2b_prod.ASIENTOCONTABLE A WHERE A.ASIENTONUMERO='51635'; /*DESC 216 A 211*/
#-52190225
#666.876.134
#649.938.256
#631.623.787
#614.685.909

SELECT * FROM K2B_PREPROD.ASIENTOCONTABLE A2 WHERE A2.ASIENTOPERIODOCIERREID='216'
AND (A2.`ASIENTOFECHA` >= '2023-08-01') AND (A2.`ASIENTOFECHA` <= '2023-08-31');

SELECT * FROM k2b_preprod.CUENTACONTABLE C;
4.1.1.2.2.21

SELECT T1.`ASIENTOID`,
       T2.ASIENTONUMERO,
       T2.`ASIENTOESTADO`,
       T2.`ASIENTOFECHA`,
       T2.`ASIENTOPERIODOCIERREID`,
       T1.`CUENTACONTABLEID`,
       T1.`ASIENTODETIMPCALMONEDALOCAL`,
       T1.`ASIENTODETIMPCALMONEDAEXTRANJE`,
       T1.`ASIENTODETIMPCALMONEDACONSOLID`,
       T1.`ASIENTODETID`
FROM (k2b_preprod.`ASIENTOCONTABLEDETALLE` T1 INNER JOIN k2b_preprod.`ASIENTOCONTABLE` T2 ON T2.`ASIENTOID` = T1.`ASIENTOID`)
WHERE (T1.`CUENTACONTABLEID` = 743)
  AND (T2.`ASIENTOFECHA` >= '2023-08-01')
  AND (T2.`ASIENTOFECHA` <= '2023-08-31')
  AND (T2.`ASIENTOPERIODOCIERREID` = 211)
  AND (T2.`ASIENTOESTADO` = 'ACT')
ORDER BY T1.`CUENTACONTABLEID`;
###########################################################################################################################
SELECT * FROM K2B_PROD.ASIENTOCONTABLE A WHERE A.ASIENTONUMERO IN ('51578','51581','51622','51628','51633','51545');

UPDATE K2B_PROD.ASIENTOCONTABLE T
SET T.ASIENTOPERIODOCIERREID = 211
WHERE T.ASIENTOID = 59370;

UPDATE K2B_PROD.ASIENTOCONTABLE T
SET T.ASIENTOPERIODOCIERREID = 211
WHERE T.ASIENTOID = 59430;

UPDATE K2B_PROD.ASIENTOCONTABLE T
SET T.ASIENTOPERIODOCIERREID = 211
WHERE T.ASIENTOID = 59419;
#-----------
SELECT * FROM K2B_PROD.ASIENTOCONTABLE A WHERE A.ASIENTONUMERO IN ('51133','51464');
UPDATE K2B_PROD.ASIENTOCONTABLE T
SET T.ASIENTOPERIODOCIERREID = 211
WHERE T.ASIENTOID = 58893;

UPDATE K2B_PROD.ASIENTOCONTABLE T
SET T.ASIENTOPERIODOCIERREID = 211
WHERE T.ASIENTOID = 59250;

SELECT * FROM K2B_PREPROD.ASIENTOCONTABLEDETALLE A WHERE A.ASIENTOID IN ('59335', '59370', '59377', '59419', '59425', '59430');
#---------------------------------------------------------------------------------
SELECT * FROM k2b_preprod.ASIENTOCONTABLE A WHERE A.ASIENTONUMERO IN ('51581','51628','51545','51485','47506','51461');
SELECT * FROM K2B_PREPROD.ASIENTOCONTABLEDETALLE A WHERE A.ASIENTOID IN ('54988','59247','59271','59335','59377','59425');
#---------------------------------------------------------------------------------
SELECT * FROM K2B_PROD.ASIENTOCONTABLE A WHERE A.ASIENTONUMERO IN ('51578','51581','51622','51628','51633','51545','51132','51133','51461');
SELECT * FROM K2B_PROD.ASIENTOCONTABLEDETALLE A WHERE A.ASIENTOID IN ('58892','58893','59247','59335','59370','59377','59419','59425','59430');
#se cambia asiento fecha y se iguala a la de valor de 21-09 al 31-08
UPDATE K2B_PROD.ASIENTOCONTABLE T
SET T.ASIENTOFECHA            = '2023-08-31',
    T.ASIENTOFECHAHORAINGRESO = '2023-09-19 00:00:00'
WHERE T.ASIENTOID = 58892;

UPDATE K2B_PROD.ASIENTOCONTABLE T
SET T.ASIENTOFECHA            = '2023-08-31',
    T.ASIENTOFECHAHORAINGRESO = '2023-09-19 00:00:00'
WHERE T.ASIENTOID = 58893;

UPDATE K2B_PROD.ASIENTOCONTABLE T
SET T.ASIENTOFECHA = '2023-08-01'
WHERE T.ASIENTOID = 59370;

UPDATE K2B_PROD.ASIENTOCONTABLE T
SET T.ASIENTOFECHA = '2023-08-01'
WHERE T.ASIENTOID = 59377;

UPDATE K2B_PROD.ASIENTOCONTABLE T
SET T.ASIENTOFECHA            = '2023-08-01',
    T.ASIENTOFECHAHORAINGRESO = '2023-09-21 14:57:04'
WHERE T.ASIENTOID = 59335;

UPDATE K2B_PROD.ASIENTOCONTABLE T
SET T.ASIENTOFECHA            = '2023-08-01',
    T.ASIENTOFECHAHORAINGRESO = '2023-09-22 00:00:00'
WHERE T.ASIENTOID = 59419;

UPDATE K2B_PROD.ASIENTOCONTABLE T
SET T.ASIENTOFECHA = '2023-08-31'
WHERE T.ASIENTOID = 59247;

UPDATE K2B_PROD.ASIENTOCONTABLE T
SET T.ASIENTOFECHA            = '2023-08-01',
    T.ASIENTOFECHAHORAINGRESO = '2023-09-22 00:00:00'
WHERE T.ASIENTOID = 59425;

UPDATE K2B_PROD.ASIENTOCONTABLE T
SET T.ASIENTOFECHA            = '2023-08-01',
    T.ASIENTOFECHAHORAINGRESO = '2023-09-22 00:00:00'
WHERE T.ASIENTOID = 59430;
#------------------------------------------------------
SELECT * FROM K2B_PROD.ASIENTOCONTABLE A
WHERE (A.`ASIENTOFECHA` >= '2023-08-01') AND (A.`ASIENTOFECHA` <= '2023-08-31') AND A.ASIENTOPERIODOCIERREID= 216;
SELECT * FROM K2B_PREPROD.ASIENTOCONTABLE A WHERE A.ASIENTONUMERO IN ('51475','51623','51634');
SELECT * FROM K2B_PROD.ASIENTOCONTABLE A WHERE A.ASIENTONUMERO IN ('51475','51623','51634');
#SE CAMBIA ESTOS ASIENTOS PERIODO DE CIERRE Y FECHA ASIENTO IGUALNADO A SU VALOR; 51636 Y 51627
SELECT * FROM k2b_prod.ASIENTOCONTABLE A WHERE A.ASIENTONUMERO IN ('51636','51627');
SELECT * FROM k2b_preprod.ASIENTOCONTABLEDETALLE A WHERE A.ASIENTOID IN (59424,59433);

UPDATE K2B_PROD.ASIENTOCONTABLE T
SET T.ASIENTOPERIODOCIERREID = 211 WHERE T.ASIENTOID = 59433;

UPDATE K2B_PROD.ASIENTOCONTABLE T
SET T.ASIENTOFECHA = '2023-08-07', T.ASIENTOPERIODOCIERREID = 211 WHERE T.ASIENTOID = 59424;
/*--------------------------------------------------------------------
  SE CAMBIA FECHA DE INGRESO DEL 01-08 IGUALANDO A SU FECHA DE CONFIRMACIÓN */
SELECT * FROM k2b_prod.ASIENTOCONTABLE A WHERE A.ASIENTONUMERO IN ('51467');
SELECT * FROM k2b_prod.ASIENTOCONTABLEDETALLE A WHERE A.ASIENTOID IN ('59253');
UPDATE k2b_prod.ASIENTOCONTABLE T
SET T.ASIENTOFECHAHORAINGRESO = '2023-09-21 11:00:11'
WHERE T.ASIENTOID = 59253;
/*-----------------------------------------------------------------------
  CASO CONCILIACIONES SOBRE EXTORNO POR db. REFERENTE A LA CUENTA AFECTADA==1.1.1.2.1.09 - BANCO CITIBANK*/
SELECT * FROM K2B_PROD.ASIENTOCONTABLE A WHERE A.ASIENTONUMERO IN ('51475', '51467');
UPDATE K2B_PROD.ASIENTOCONTABLE T
SET T.ASIENTOFECHA           = '2023-08-31',
    T.ASIENTOPERIODOCIERREID = 211
WHERE T.ASIENTOID = 59261;

SELECT * FROM K2B_PROD.ASIENTOCONTABLE A WHERE A.ASIENTONUMERO IN ('51582', '51623');
UPDATE K2B_PROD.ASIENTOCONTABLE T
SET T.ASIENTOFECHA           = '2023-08-01',
    T.ASIENTOPERIODOCIERREID = 211
WHERE T.ASIENTOID = 59420;

SELECT * FROM K2B_PROD.ASIENTOCONTABLE A WHERE A.ASIENTONUMERO IN ('51629', '51634');
UPDATE K2B_PROD.ASIENTOCONTABLE T
SET T.ASIENTOFECHA           = '2023-08-01',
    T.ASIENTOPERIODOCIERREID = 211
WHERE T.ASIENTOID = 59431;

SHOW ENGINE INNODB STATUS;

SELECT COUNT(1),
       A.ASIENTOPERIODOCIERREID,
       (SELECT PP.PERIODOCODIGO
        FROM PERIODO PP
        WHERE PP.PERIODOID IN (SELECT P.PERIODOID FROM PERIODOCIERRE P WHERE P.PERIODOCIERREID = A.ASIENTOPERIODOCIERREID)) PERIODO_DESCRI
FROM ASIENTOCONTABLE A
WHERE A.ASIENTOFECHA BETWEEN '2023-08-01' AND '2023-08-31'
GROUP BY A.ASIENTOPERIODOCIERREID
UNION
SELECT COUNT(1),
       A.ASIENTOPERIODOCIERREID,
       (SELECT PP.PERIODOCODIGO
        FROM PERIODO PP
        WHERE PP.PERIODOID IN (SELECT P.PERIODOID FROM PERIODOCIERRE P WHERE P.PERIODOCIERREID = A.ASIENTOPERIODOCIERREID)) PERIODO_DESCRI
FROM ASIENTOCONTABLE A
WHERE A.ASIENTOFECHA BETWEEN '2023-09-01' AND '2023-09-30'
GROUP BY A.ASIENTOPERIODOCIERREID
UNION
SELECT COUNT(1),
       A.ASIENTOPERIODOCIERREID,
       (SELECT PP.PERIODOCODIGO
        FROM PERIODO PP
        WHERE PP.PERIODOID IN (SELECT P.PERIODOID FROM PERIODOCIERRE P WHERE P.PERIODOCIERREID = A.ASIENTOPERIODOCIERREID)) PERIODO_DESCRI
FROM ASIENTOCONTABLE A
WHERE A.ASIENTOFECHA BETWEEN '2023-10-01' AND '2023-10-31'
GROUP BY A.ASIENTOPERIODOCIERREID;

SELECT * FROM K2B_PROD.ASIENTOCONTABLE A WHERE A.ASIENTONUMERO IN ('51582','51623','51629','51634','51467','51475');

SELECT *
FROM (((`AENTRY` T1 INNER JOIN `AENTITY` T4 ON T4.`AEID` = T1.`AEID`) INNER JOIN `ATABLE` T3 ON T3.`ATID` = T1.`ATID`) INNER JOIN `AUSER` T2 ON T2.`AUID` = T1.`AUID`)
WHERE (T1.`AENTRYDATE` <= '2023-09-29 23:59:59')
  AND (T1.`AENTRYDATE` >= '2023-09-28 00:00:00');

SELECT T1.`ATID`, T2.`ATDESCRIPTION`, T1.`AEID`
FROM (`AENTTABLE` T1 INNER JOIN `ATABLE` T2 ON T2.`ATID` = T1.`ATID`)
WHERE T1.`AEID` = 0
ORDER BY T2.`ATDESCRIPTION`;
SELECT `AEId`, `AEDescription` FROM `AEntity` ORDER BY `AEDescription`;
SELECT `AUId`, `AUName` FROM `AUser` ORDER BY `AUName`
SELECT T1.`ATId`, T2.`ATDescription`, T1.`AEId` FROM (`AEntTable` T1 INNER JOIN `ATable` T2 ON T2.`ATId` = T1.`ATId`) WHERE T1.`AEId` = 0 ORDER BY T2.`ATDescription`
SELECT `AEId`, `AEDescription` FROM `AEntity` ORDER BY `AEDescription`
SELECT `AUId`, `AUName` FROM `AUser` ORDER BY `AUName`

SELECT `APPPRMNAME`,
       `APPID`,
       `REPID`,
       `APPPRMDEFTYPE`,
       `APPPRMGUID`,
       `APPPRMPGMNAME`,
       `APPPRMPGMPAR`,
       `APPPRMTOKENTYPEGUID`
FROM `APPPERMISSION`
WHERE `REPID` = 2
  AND `APPID` = 2
  AND `APPPRMNAME` = 'atable_Execute'
ORDER BY `REPID`, `APPID`, `APPPRMNAME`
LIMIT 1;
SELECT T1.`AEID`,
       T1.`ATID`,
       T1.`AUID`,
       T1.`AENTRYID`,
       T1.`AENTRYCAPPWS`,
       T1.`AENTRYOSUSER`,
       T1.`AENTRYDBMSWS`,
       T1.`AENTRYDBMSUSER`,
       T1.`AUTLID`,
       T4.`AUNAME`,
       T3.`ATDESCRIPTION`,
       T2.`AEDESCRIPTION`,
       T1.`AENTRYOPERATION`,
       T1.`AENTRYDATE`
FROM (((`AENTRY` T1 INNER JOIN `AENTITY` T2 ON T2.`AEID` = T1.`AEID`) INNER JOIN `ATABLE` T3 ON T3.`ATID` = T1.`ATID`) INNER JOIN `AUSER` T4 ON T4.`AUID` = T1.`AUID`)
WHERE (T1.`AENTRYDATE` <= '2023-09-29 23:59:59')
  AND (T1.`AENTRYDATE` >= '2023-09-28 00:00:00')
ORDER BY T1.`AENTRYDATE` DESC
LIMIT 0, 11;

SELECT * FROM k2b_prod.ATABLE A;

select  count(1),
       a.AsientoPeriodoCierreId ,
       (select pp.PeriodoCodigo
		from periodo pp
		where pp.PeriodoId in (select p.PeriodoId  from periodocierre p where p.PeriodoCierreId =a.AsientoPeriodoCierreId )
		) PERIODO_DESCRIPCION
from asientocontable a
where a.AsientoFecha between '2023-09-01' and '2023-09-30'
group by a.AsientoPeriodoCierreId;
#------------------------------------------------------------
SELECT * FROM BIENACTIVOFIJO b WHERE BienActivoFijoProductoId IN (2756,3642);
#------------------------------------------------------------
SELECT * FROM k2b_prod.CLIENTE C;


SELECT * FROM k2b_prod.CUENTAAUXILIARCONTABLE C;

SELECT *
FROM `PERIODOCIERRE`
WHERE PERIODOCIERREID IN (SELECT PERIODOCIERREID FROM `EJERCICIOCONTABLEPERIODOCIERRE` WHERE EJERCICIOCONTABLEID = 4);
#habilita extorno
update `tipotransaccion` set tipotransaccionmodoejecucion = 'INTERACTIVA' where `TipotransaccionCodigo` IN ('CIERRERESULTADOS');
#desabilita extorno
update `tipotransaccion` set tipotransaccionmodoejecucion = 'BATCH' where `TipotransaccionCodigo` IN ('CIERRERESULTADOS');

 delete from saldocontable  where SaldoContablePeriodoId = 126;
select *  from saldocontable  where SaldoContablePeriodoId=126;

SHOW VARIABLES LIKE '%max_allowed_packet%';

SET GLOBAL max_allowed_packet = 3221225472;

#---query mayor
SELECT T1.`CUENTAAUXCONTABLEID`,
       T1.`CENTROCOSTOID`,
       T1.`ITEMPROYECTOID`,
       T1.`CUENTACONTABLEID`,
       T8.`ASIENTOEMPID`,
       T1.`CRITERIOCONTABLECODIGO`,
       T8.`ASIENTOESTADO`,
       T9.`TIPOTRANSACCIONMODOEJECUCIONBA` AS TIPOASIENTOMODOEJECUCIONBATCHC,
       T8.`ASIENTOFECHA`,
       T1.`MONEDACODIGO`,
       T5.`CUENTACONTABLECODIGO`,
       T7.`TIPODOCUMENTOCODIGO`            AS ASIENTODETTIPODOCUMENTOCODIGO,
       T10.`TIPODOCUMENTOCODIGO`           AS ASIENTOTIPODOCUMENTOCODIGO,
       T1.`ASIENTODETOBSERVACIONES`,
       T8.`ASIENTOOBSERVACIONES`,
       T9.`TIPOTRANSACCIONNOMBRE`          AS TIPOASIENTODESCRIPCION,
       T1.`ASIENTODETVTOFINANCIERODOCUMEN`,
       T1.`ASIENTODETFECHAVALOR`,
       T2.`CUENTAAUXCONTABLEDESCRIPCION`,
       T4.`ITEMPROYECTONOMBRE`,
       T3.`CENTROCOSTONOMBRE`,
       T6.`MONEDASIMBOLO`,
       T1.`ASIENTODETIMPCALMONEDAORIGEN`,
       T8.`ASIENTONUMERO`,
       T8.`TIPOASIENTOCODIGO`              AS TIPOASIENTOCODIGO,
       T8.`ASIENTOTIPODOCUMENTOID`         AS ASIENTOTIPODOCUMENTOID,
       T10.`ENTIDADCODIGO`                 AS ASIENTOENTIDADCODIGO,
       T8.`ASIENTODOCUMENTOID`,
       T8.`ASIENTODOCUMENTOCODIGOEXTERNO`,
       T10.`TIPODOCUMENTOINTERNOK2B`       AS ASIENTOTIPODOCUMENTOINTERNOK2B,
       T1.`ASIENTODETTIPODOCUMENTOID`      AS ASIENTODETTIPODOCUMENTOID,
       T7.`ENTIDADCODIGO`                  AS ASIENTODETENTIDADCODIGO,
       T1.`ASIENTODETDOCUMENTOID`,
       T1.`ASIENTODETDOCUMENTOCODIGOEXTER`,
       T7.`TIPODOCUMENTOINTERNOK2B`        AS ASIENTODETTIPODOCUMENTOINTERNO,
       T1.`ASIENTODETIMPORTEMONEDACONSOLI`,
       T1.`ASIENTODETIMPORTEMONEDAEXTRANJ`,
       T1.`ASIENTODETTIPOMOVIMIENTO`,
       T1.`ASIENTODETIMPORTEMONEDALOCAL`,
       T8.`ASIENTOEXTORNO`,
       T1.`ASIENTOID`,
       T1.`ASIENTODETID`
FROM (((((((((`ASIENTOCONTABLEDETALLE` T1 LEFT JOIN `CUENTAAUXILIARCONTABLE` T2 ON T2.`CUENTAAUXCONTABLEID` = T1.`CUENTAAUXCONTABLEID`) LEFT JOIN `CENTROCOSTO` T3 ON T3.`CENTROCOSTOID` = T1.`CENTROCOSTOID`) LEFT JOIN `ITEMPROYECTO` T4 ON T4.`ITEMPROYECTOID` = T1.`ITEMPROYECTOID`) INNER JOIN `CUENTACONTABLE` T5 ON T5.`CUENTACONTABLEID` = T1.`CUENTACONTABLEID`) INNER JOIN `MONEDA` T6 ON T6.`MONEDACODIGO` = T1.`MONEDACODIGO`) LEFT JOIN `TIPODOCUMENTO` T7
         ON T7.`TIPODOCUMENTOID` = T1.`ASIENTODETTIPODOCUMENTOID`) INNER JOIN `ASIENTOCONTABLE` T8 ON T8.`ASIENTOID` = T1.`ASIENTOID`) INNER JOIN `TIPOTRANSACCION` T9 ON T9.`TIPOTRANSACCIONCODIGO` = T8.`TIPOASIENTOCODIGO`) LEFT JOIN `TIPODOCUMENTO` T10 ON T10.`TIPODOCUMENTOID` = T8.`ASIENTOTIPODOCUMENTOID`)
WHERE (T1.`CUENTACONTABLEID` IN (157,156))
  #AND (T8.`ASIENTOEMPID` = 1)
  AND (T1.`CRITERIOCONTABLECODIGO` = 'DEV')
  AND (T8.`ASIENTOESTADO` = 'ACT')
  AND (T8.`ASIENTOFECHA` >= '2024-09-01')
  AND (T8.`ASIENTOFECHA` <= '2024-09-30') AND T8.ASIENTONUMERO=121782
ORDER BY T8.`ASIENTOFECHA`, T8.`TIPOASIENTOCODIGO`, T8.`ASIENTONUMERO`;

SELECT * FROM k2b_prod.CUENTACONTABLE C WHERE C.CUENTACONTABLECODIGO IN ('2.1.1.3.1.07');
SELECT * FROM k2b_prod.ASIENTOCONTABLE A;
SELECT * FROM k2b_prod.ASIENTOCONTABLEDETALLE A WHERE A.ASIENTOID = 133663;
SELECT * FROM k2b_prod.TIPOASIENTOCONTABLE T WHERE T.TIPOASIENTOCODIGO LIKE '%VISA%';
#-------DEPURAR SIMULACRO
    TRUNCATE TABLE k2b_prod.instanciaproceso;
#k2b_prod.entidadinstanciadatosadjuntos
#k2b_prod.instanciaproceso;

select * FROM k2b_prod.BIENACTIVOFIJO B;

SELECT * FROM ASIENTOCONTABLEDETALLE;
SET GLOBAL max_allowed_packet = 8073741824;

SHOW VARIABLES LIKE 'max_allowed_packet';