SHOW FULL PROCESSLIST;
SHOW PROCESSLIST;
/*En la columna State tiene que decir = Locked si está bloqueado y en la columna Info muestra la query que está ejecutando-.*/
SELECT *
FROM INFORMATION_SCHEMA.PROCESSLIST;/*--Esto muestra casi lo mismo...*/
SHOW INDEX FROM K2B_PROD.ASIENTOCONTABLE;
/*--muestra los índices creados sobre la tabla que quieras consultar...*/
--
SHOW ENGINE INNODB STATUS;
--
SELECT NOW();/*ver la hora de la db*/
SET GLOBAL general_log = 1; /*activar log*/
SELECT VERSION();
-- ver version mysql
#para ver tamaño de tablas
/*--**Tamaño de Tablas en la BD**--*/
SELECT T.TABLE_SCHEMA AS BD, T.TABLE_NAME AS TABLA, ROUND((T.DATA_LENGTH + T.INDEX_LENGTH) / 1024 / 1024, 2) AS TAMAÑO_MB,
ROUND((T.DATA_LENGTH + T.INDEX_LENGTH) / 1024 / 1024 / 1024, 2) AS TAMAÑO_GB
FROM INFORMATION_SCHEMA.TABLES T
ORDER BY (T.DATA_LENGTH + T.INDEX_LENGTH) DESC;
#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*Sentencia para actualización de fechas de Activo Fijo K2B*/
UPDATE BIENACTIVOFIJO
SET BIENACTIVOFIJOFECHAACTIVACION = BIENACTIVOFIJOFECHAADQUISICION
WHERE BIENACTIVOFIJOFECHAADQUISICION >= '2021-01-01'
  AND BIENACTIVOFIJOFECHAADQUISICION > BIENACTIVOFIJOFECHAACTIVACION;
#---------------------------------------------------------------------------------------------------------------
/*----UPDATE para corregir configuración módulo de planificación K2B*/
UPDATE ITEMAFECTACIONAFECTABLE
SET ITEMAFECTABLEMODOAFECTACION = 'DIRECTO'
WHERE ITEMAFECTABLEMODOAFECTACION = 'INDIRECTO'
  AND TIPOAFECTACIONCODIGO = 'PRESUPUESTAL';
UPDATE ITEMCOSTORESTRICCION
SET ITEMCOSTORESTITEMAFECTABLEMODO = 'DIRECTO'
WHERE ITEMCOSTORESTITEMAFECTABLEMODO = 'INDIRECTO'
  AND ITEMCOSTORESTTIPOAFECTACIONCOD = 'PRESUPUESTAL';
/*realizamos un cambio con el proveedor Repair-SMD #43969*/
UPDATE ITEMAFECTACIONAFECTABLE
SET ITEMAFECTABLEPRESUPUESTOHABILI = 1
WHERE ITEMAFECTABLEPRESUPUESTOHABILI = 0
  AND TIPOAFECTACIONCODIGO = 'PRESUPUESTAL';
/*para validar una solución a un error de POS*/
SELECT *
FROM MOVIMIENTOSTOCK M,
     MOVIMIENTOSTOCKDETALLE D,
     MOVIMIENTOSTOCKINVENTARIO MI
WHERE MI.MOVSTOCKID = D.MOVSTOCKID
  AND MI.MOVSTOCKDETID = D.MOVSTOCKDETID
  AND D.MOVSTOCKID = M.MOVSTOCKID
  AND MOVSTOCKESTADOPROCESOINGRESO = 'NoCompletado';
/*--Habilitacion de notificaciones por correo: solicitudes de fondos*/
SELECT WFPRCID, WFTASKCOD, WFTASKNAME, WFTASKDSC, WFTASKEMAIL
FROM WFTASK
WHERE WFPRCID = 47
  AND WFTASKCOD IN (22, 29, 184, 204);
UPDATE WFTASK
SET WFTASKEMAIL ='Y'
WHERE WFPRCID = 47
  AND WFTASKCOD IN (22, 29, 184, 204);
/*---Sentencia para actualización de fechas de Activo Fijo K2B*/
UPDATE BIENACTIVOFIJO
SET BIENACTIVOFIJOFECHAACTIVACION = BIENACTIVOFIJOFECHAADQUISICION
WHERE BIENACTIVOFIJOFECHAADQUISICION >= '2021-01-01'
  AND BIENACTIVOFIJOFECHAADQUISICION > BIENACTIVOFIJOFECHAACTIVACION;
/*---Con referencia al problema con el deposito Lo que se debe hacer para solucionar esto es modificar por BD el tipo de depósito*/
UPDATE DEPOSITO
SET TIPODEPOSITOCODIGO = 'TRANSITO'
WHERE DEPOSITOID = 56
  AND DEPOSITONOMBRE LIKE 'Transito%';
/*Y  lo que me pidieron recalcar es : El depósito de tipo Transito sirve para mostrar que el material está en viaje desde CA origen a uno de destino. No se debe permitir cambiar el tipo o eliminar depósitos en Tránsito
Todos los CA deben tener un solo depósito de tipo Tránsito.*/
/*-------------------------------------------------------------------------------------------*/
/*Con este cambio la misma dejará de reservar stock cada vez que se realice un movimiento utilizando la misma.*/
/*1.*/
UPDATE TIPOTRANSACCIONSTOCK
SET TIPOTRNSTKTIPOSTKRESERVACODIGO = NULL
WHERE TIPOTRNSTKCODIGO = 'TRANSFERENCIA';
/*2.*/ UPDATE TIPOTRANSACCIONSTOCK
       SET TIPOTRNSTKRESERVA = 0
       WHERE TIPOTRNSTKCODIGO = 'TRANSFERENCIA';
/*-------------------------------------------------------------------------------------------*/
SET GLOBAL general_log = 1;
SET GLOBAL LOG_OUTPUT = 'TABLE';
SET GLOBAL slow_query_log = 'ON';

SELECT *
FROM MYSQL.GENERAL_LOG GL;
TRUNCATE MYSQL.GENERAL_LOG;

SELECT *
FROM INFORMATION_SCHEMA.TRIGGERS;
#----
SELECT COUNT(1),
       A.ASIENTOPERIODOCIERREID,
       (SELECT PP.PERIODOCODIGO
        FROM PERIODO PP
        WHERE PP.PERIODOID IN (SELECT P.PERIODOID FROM PERIODOCIERRE P WHERE P.PERIODOCIERREID = A.ASIENTOPERIODOCIERREID)) PERIODO_DESCRI
FROM ASIENTOCONTABLE A
WHERE A.ASIENTOFECHA BETWEEN '2023-08-01' AND '2023-08-31'
GROUP BY A.ASIENTOPERIODOCIERREID
UNION
SELECT COUNT(1),
       A.ASIENTOPERIODOCIERREID,
       (SELECT PP.PERIODOCODIGO
        FROM PERIODO PP
        WHERE PP.PERIODOID IN (SELECT P.PERIODOID FROM PERIODOCIERRE P WHERE P.PERIODOCIERREID = A.ASIENTOPERIODOCIERREID)) PERIODO_DESCRI
FROM ASIENTOCONTABLE A
WHERE A.ASIENTOFECHA BETWEEN '2023-09-01' AND '2023-09-30'
GROUP BY A.ASIENTOPERIODOCIERREID
UNION
SELECT COUNT(1),
       A.ASIENTOPERIODOCIERREID,
       (SELECT PP.PERIODOCODIGO
        FROM PERIODO PP
        WHERE PP.PERIODOID IN (SELECT P.PERIODOID FROM PERIODOCIERRE P WHERE P.PERIODOCIERREID = A.ASIENTOPERIODOCIERREID)) PERIODO_DESCRI
FROM ASIENTOCONTABLE A
WHERE A.ASIENTOFECHA BETWEEN '2023-10-01' AND '2023-10-31'
GROUP BY A.ASIENTOPERIODOCIERREID;

#------------------------------------------------------------
SELECT *
FROM BIENACTIVOFIJO B
WHERE BIENACTIVOFIJOPRODUCTOID IN (2756, 3642);
#------------------------------------------------------------
SELECT *
FROM `PERIODOCIERRE`
WHERE PERIODOCIERREID IN (SELECT PERIODOCIERREID FROM `EJERCICIOCONTABLEPERIODOCIERRE` WHERE EJERCICIOCONTABLEID = 4);
#habilita extorno
UPDATE `TIPOTRANSACCION`
SET TIPOTRANSACCIONMODOEJECUCION = 'INTERACTIVA'
WHERE `TIPOTRANSACCIONCODIGO` IN ('CIERRERESULTADOS');
#desabilita extorno
UPDATE `TIPOTRANSACCION`
SET TIPOTRANSACCIONMODOEJECUCION = 'BATCH'
WHERE `TIPOTRANSACCIONCODIGO` IN ('CIERRERESULTADOS');

DELETE
FROM SALDOCONTABLE
WHERE SALDOCONTABLEPERIODOID = 126;
SELECT *
FROM SALDOCONTABLE
WHERE SALDOCONTABLEPERIODOID = 126;

SHOW VARIABLES LIKE '%max_allowed_packet%';

SET GLOBAL max_allowed_packet = 3221225472;

#---query mayor
SELECT T1.`CUENTAAUXCONTABLEID`, T1.`CENTROCOSTOID`, T1.`ITEMPROYECTOID`, T1.`CUENTACONTABLEID`, T8.`ASIENTOEMPID`, T1.`CRITERIOCONTABLECODIGO`, T8.`ASIENTOESTADO`, T9.`TIPOTRANSACCIONMODOEJECUCIONBA` AS TIPOASIENTOMODOEJECUCIONBATCHC, T8.`ASIENTOFECHA`, T1.`MONEDACODIGO`, T5.`CUENTACONTABLECODIGO`, T7.`TIPODOCUMENTOCODIGO`            AS ASIENTODETTIPODOCUMENTOCODIGO, T10.`TIPODOCUMENTOCODIGO`           AS ASIENTOTIPODOCUMENTOCODIGO, T1.`ASIENTODETOBSERVACIONES`, T8.`ASIENTOOBSERVACIONES`, T9.`TIPOTRANSACCIONNOMBRE`          AS TIPOASIENTODESCRIPCION, T1.`ASIENTODETVTOFINANCIERODOCUMEN`, T1.`ASIENTODETFECHAVALOR`, T2.`CUENTAAUXCONTABLEDESCRIPCION`, T4.`ITEMPROYECTONOMBRE`, T3.`CENTROCOSTONOMBRE`, T6.`MONEDASIMBOLO`, T1.`ASIENTODETIMPCALMONEDAORIGEN`, T8.`ASIENTONUMERO`, T8.`TIPOASIENTOCODIGO`              AS TIPOASIENTOCODIGO, T8.`ASIENTOTIPODOCUMENTOID`         AS ASIENTOTIPODOCUMENTOID, T10.`ENTIDADCODIGO`                 AS ASIENTOENTIDADCODIGO, T8.`ASIENTODOCUMENTOID`, T8.`ASIENTODOCUMENTOCODIGOEXTERNO`, T10.`TIPODOCUMENTOINTERNOK2B`       AS ASIENTOTIPODOCUMENTOINTERNOK2B, T1.`ASIENTODETTIPODOCUMENTOID`      AS ASIENTODETTIPODOCUMENTOID, T7.`ENTIDADCODIGO`                  AS ASIENTODETENTIDADCODIGO, T1.`ASIENTODETDOCUMENTOID`, T1.`ASIENTODETDOCUMENTOCODIGOEXTER`, T7.`TIPODOCUMENTOINTERNOK2B`        AS ASIENTODETTIPODOCUMENTOINTERNO, T1.`ASIENTODETIMPORTEMONEDACONSOLI`, T1.`ASIENTODETIMPORTEMONEDAEXTRANJ`, T1.`ASIENTODETTIPOMOVIMIENTO`, T1.`ASIENTODETIMPORTEMONEDALOCAL`, T8.`ASIENTOEXTORNO`, T1.`ASIENTOID`, T1.`ASIENTODETID`
FROM (((((((((`ASIENTOCONTABLEDETALLE` T1 LEFT JOIN `CUENTAAUXILIARCONTABLE` T2 ON T2.`CUENTAAUXCONTABLEID` = T1.`CUENTAAUXCONTABLEID`) LEFT JOIN `CENTROCOSTO` T3 ON T3.`CENTROCOSTOID` = T1.`CENTROCOSTOID`) LEFT JOIN `ITEMPROYECTO` T4 ON T4.`ITEMPROYECTOID` = T1.`ITEMPROYECTOID`) INNER JOIN `CUENTACONTABLE` T5 ON T5.`CUENTACONTABLEID` = T1.`CUENTACONTABLEID`) INNER JOIN `MONEDA` T6 ON T6.`MONEDACODIGO` = T1.`MONEDACODIGO`) LEFT JOIN `TIPODOCUMENTO` T7
         ON T7.`TIPODOCUMENTOID` = T1.`ASIENTODETTIPODOCUMENTOID`) INNER JOIN `ASIENTOCONTABLE` T8 ON T8.`ASIENTOID` = T1.`ASIENTOID`) INNER JOIN `TIPOTRANSACCION` T9 ON T9.`TIPOTRANSACCIONCODIGO` = T8.`TIPOASIENTOCODIGO`) LEFT JOIN `TIPODOCUMENTO` T10 ON T10.`TIPODOCUMENTOID` = T8.`ASIENTOTIPODOCUMENTOID`)
WHERE (T1.`CUENTACONTABLEID` IN (157, 156))
  #AND (T8.`ASIENTOEMPID` = 1)
  AND (T1.`CRITERIOCONTABLECODIGO` = 'DEV')
  AND (T8.`ASIENTOESTADO` = 'ACT')
  AND (T8.`ASIENTOFECHA` >= '2024-09-01')
  AND (T8.`ASIENTOFECHA` <= '2024-09-30')
  AND T8.ASIENTONUMERO = 121782
ORDER BY T8.`ASIENTOFECHA`, T8.`TIPOASIENTOCODIGO`, T8.`ASIENTONUMERO`;

#-------DEPURAR SIMULACRO
TRUNCATE TABLE K2B_PROD.INSTANCIAPROCESO;
#k2b_prod.entidadinstanciadatosadjuntos
#k2b_prod.instanciaproceso;

#Monitorea el uso con:
SHOW ENGINE INNODB STATUS;
#y ajusta si ves que el pool no se utiliza completamente o hay demasiadas lecturas de disco.
#--------------------------------------
#Usa este comando para analizar la eficiencia de la Query Cache:
SHOW STATUS LIKE 'Qcache%';
#Revisa valores como Qcache_hits y Qcache_inserts para ver cuántas consultas se benefician de la caché.
SELECT USER, HOST, PLUGIN
FROM MYSQL.USER
WHERE USER = 'root';

#PERMISO ROOT
GRANT ALL PRIVILEGES ON K2B_PROD_GAM.* TO 'ROOT'@'%';
FLUSH PRIVILEGES;

#movimiento stock
SELECT T1.`MOVSTOCKTIPOMOVIMIENTO`, T1.`MOVSTOCKCENTROALMACENAJEID`, T1.`MOVSTOCKEMPRESAID`, T1.`MOVSTOCKFECHA`, T1.`MOVSTOCKPERSONAID`          AS MOVSTOCKPERSONAID, T1.`MOVSTOCKESTADOPROCESOINGRESO`, T1.`MOVSTOCKFECHAVALOR`, T2.`PERSONANOMBRE`              AS MOVSTOCKPERSONANOMBRE, T3.`TIPOTRANSACCIONNOMBRE`      AS MOVSTOCKTIPOTRNSTKNOMBRE, T1.`MOVSTOCKCODIGO`, T1.`MOVSTOCKID`, T1.`MOVSTOCKTIPOTRNSTKCODIGO`   AS MOVSTOCKTIPOTRNSTKCODIGO, T4.`TIPODOCUMENTONOMBRE`        AS MOVSTOCKTIPODOCUMENTOREFNOMBRE, T1.`MOVSTOCKTIPODOCUMENTOREFID` AS MOVSTOCKTIPODOCUMENTOREFID, T1.`MOVSTOCKDOCUMENTOREFID`, T1.`MOVSTOCKDOCUMENTOREFNUMEROEXTE`
FROM (((`MOVIMIENTOSTOCK` T1 LEFT JOIN `PERSONA` T2 ON T2.`PERSONAID` = T1.`MOVSTOCKPERSONAID`)
    INNER JOIN `TIPOTRANSACCION` T3 ON T3.`TIPOTRANSACCIONCODIGO` = T1.`MOVSTOCKTIPOTRNSTKCODIGO`)
    LEFT JOIN `TIPODOCUMENTO` T4 ON T4.`TIPODOCUMENTOID` = T1.`MOVSTOCKTIPODOCUMENTOREFID`)
WHERE (T1.`MOVSTOCKCENTROALMACENAJEID` = 42 AND T1.`MOVSTOCKEMPRESAID` = 1)
  AND (T1.`MOVSTOCKFECHAVALOR` <= '2024-12-30')
  AND (T1.`MOVSTOCKFECHAVALOR` >= '2024-11-30')
ORDER BY T1.`MOVSTOCKCODIGO`;

#--------------------------
SELECT *
FROM K2B_PROD.BIENACTIVOFIJO B
WHERE BIENACTIVOFIJONUMEROSERIE LIKE '%PEND%';
#------------------------------------------------
#orden stock
SELECT O.ORDENSTKFECHAVALOR, O.ORDENSTKFECHAESTIMADA, O.ORDENSTKFECHASOLICITUD, O.*
FROM K2B_PROD.ORDENSTOCK O
WHERE O.ORDENSTKCODIGO = 33820;
#movimiento sotock salida y entrada
SELECT M.MOVSTOCKFECHA, M.MOVSTOCKFECHAVALOR, M.*
FROM K2B_PROD.MOVIMIENTOSTOCK M
WHERE M.MOVSTOCKCODIGO = 158217;
#Datos AF
SELECT B.BIENACTIVOFIJOIMPORTEMONEDALOC, B.BIENACTIVOFIJOFECHAADQUISICION, B.*
FROM K2B_PROD.BIENACTIVOFIJO B
WHERE B.BIENACTIVOFIJOCODIGO #= 'AF-000438';
          IN ('AF-031517', 'AF-031518', 'AF-031519', 'AF-031531',
              'AF-034133', 'AF-034140', 'AF-040028', 'AF-040029', 'AF-040702');
#mov activo fijo
SELECT M.MOVACTIVOFIJOFECHAVALOR, M.MOVACTIVOFIJOFECHA, M.*
FROM K2B_PROD.MOVIMIENTOACTIVOFIJO M
WHERE M.MOVACTIVOFIJOCODIGO = 158217;

SELECT *
FROM K2B_PROD.BIENACTIVOFIJO
WHERE BIENACTIVOFIJOCODIGO = 'AF-036900';
#pantalla bien activo fijo.!
SELECT T1.`INVACTIVOFIJOID`, T1.`INVACTIVOFIJOBIENID`            AS INVACTIVOFIJOBIENID, T2.`BIENACTIVOFIJOCODIGO`           AS INVACTIVOFIJOBIENCODIGO, T2.`BIENACTIVOFIJONUMEROSERIE`      AS INVACTIVOFIJOBIENNUMEROSERIE, T2.`BIENACTIVOFIJODESCRIPCION`      AS INVACTIVOFIJOBIENDESCRIPCION, T2.`BIENACTIVOFIJOCONCEPTOEGREID`   AS INVACTIVOFIJOBIENCONCEPTOEGREI, T1.`INVACTIVOFIJOPRODUCTOID`        AS INVACTIVOFIJOPRODUCTOID, T3.`PRODUCTOCODIGO`                 AS INVACTIVOFIJOPRODUCTOCODIGO, T3.`PRODUCTODESCRIPCION`            AS INVACTIVOFIJOPRODUCTODESCRIPCI, T3.`PRODUCTOCODIGODESCRIPCION`      AS INVACTIVOFIJOPRODUCTOCODIGODES, T1.`INVACTIVOFIJOESTADOCONSCODIGO`, T1.`INVACTIVOFIJOBIENESCOMPUESTO`, T1.`INVACTIVOFIJOTIPOBIEN`, T1.`INVACTIVOFIJOTIPOANEXO`, T2.`BIENACTIVOFIJOGRUPO`            AS INVACTIVOFIJOBIENGRUPO, T1.`INVACTIVOFIJOBIENCOMPID`        AS INVACTIVOFIJOBIENCOMPID, T4.`BIENACTIVOFIJOCODIGO`           AS INVACTIVOFIJOBIENCOMPCODIGO, T4.`BIENACTIVOFIJONUMEROSERIE`      AS INVACTIVOFIJOBIENCOMPNUMEROSER, T4.`BIENACTIVOFIJODESCRIPCION`      AS INVACTIVOFIJOBIENCOMPDESCRIPCI, T4.`BIENACTIVOFIJOMOTIVOID`         AS INVACTIVOFIJOBIENCOMPMOTIVOID, T1.`INVACTIVOFIJOEMPRESAID`         AS INVACTIVOFIJOEMPRESAID, T5.`EMPRESANOMBRE`                  AS INVACTIVOFIJOEMPRESANOMBRE, T5.`EMPRESACODIGONOMBRE`            AS INVACTIVOFIJOEMPRESACODIGONOMB, T1.`INVACTIVOFIJOTIPOUBICACION`, T1.`INVACTIVOFIJOPERSONAID`         AS INVACTIVOFIJOPERSONAID, T1.`INVACTIVOFIJOROLCODIGO`, T6.`PERSONANOMBRE`                  AS INVACTIVOFIJOPERSONANOMBRE, T1.`INVACTIVOFIJOPERSONARESPID`     AS INVACTIVOFIJOPERSONARESPID, T7.`PERSONANOMBRE`                  AS INVACTIVOFIJOPERSONARESPNOMBRE, T1.`INVACTIVOFIJOPERSONAJURIDICAID` AS INVACTIVOFIJOPERSONAJURIDICAID, T8.`PERSONANOMBRE`                  AS INVACTIVOFIJOPERSONAJURIDICANO, T1.`INVACTIVOFIJODIRECCIONID`       AS INVACTIVOFIJODIRECCIONID, T9.`DIRECCIONDESCRIPCION`           AS INVACTIVOFIJODIRECCIONDESCRIPC, T1.`INVACTIVOFIJOLUGARFISICOID`     AS INVACTIVOFIJOLUGARFISICOID, T10.`LUGARFISICONOMBRE`             AS INVACTIVOFIJOLUGARFISICONOMBRE, T10.`LUGARFISICOCODIGONOMBRE`       AS INVACTIVOFIJOLUGARFISICOCODNOM, T1.`INVACTIVOFIJOSECTORID`          AS INVACTIVOFIJOSECTORID, T11.`SECTORNOMBRE`                  AS INVACTIVOFIJOSECTORNOMBRE, T11.`SECTORCODIGONOMBRE`            AS INVACTIVOFIJOSECTORCODIGONOMBR, T11.`SECTORENTRANSITO`              AS INVACTIVOFIJOSECTORENTRANSITO, T1.`INVACTIVOFIJOCENTROALMACENAJEI` AS INVACTIVOFIJOCENTROALMACENAJEI, T12.`CENTROALMACENAJENOMBRE`        AS INVACTIVOFIJOCENTROALMACENAJEN, T1.`INVACTIVOFIJOFECHAINICIORESGUA`, T1.`INVACTIVOFIJOFECHAFINRESGUARDO`, T1.`INVACTIVOFIJOPERIODOID`         AS INVACTIVOFIJOPERIODOID, T13.`PERIODODESCRIPCION`            AS INVACTIVOFIJOPERIODODESCRIPCIO, T1.`INVACTIVOFIJOAFECTACIONCOSTOID`
FROM ((((((((((((`INVENTARIOACTIVOFIJO` T1 INNER JOIN `BIENACTIVOFIJO` T2 ON T2.`BIENACTIVOFIJOID` = T1.`INVACTIVOFIJOBIENID`)
    LEFT JOIN `PRODUCTO` T3 ON T3.`PRODUCTOID` = T1.`INVACTIVOFIJOPRODUCTOID`)
    LEFT JOIN `BIENACTIVOFIJO` T4 ON T4.`BIENACTIVOFIJOID` = T1.`INVACTIVOFIJOBIENCOMPID`)
    INNER JOIN `EMPRESA` T5 ON T5.`EMPRESAID` = T1.`INVACTIVOFIJOEMPRESAID`)
    LEFT JOIN `PERSONA` T6 ON T6.`PERSONAID` = T1.`INVACTIVOFIJOPERSONAID`)
    LEFT JOIN `PERSONA` T7 ON T7.`PERSONAID` = T1.`INVACTIVOFIJOPERSONARESPID`)
    LEFT JOIN `PERSONA` T8 ON T8.`PERSONAID` = T1.`INVACTIVOFIJOPERSONAJURIDICAID`)
    LEFT JOIN `DIRECCION` T9 ON T9.`DIRECCIONID` = T1.`INVACTIVOFIJODIRECCIONID`)
    LEFT JOIN `LUGARFISICO` T10 ON T10.`LUGARFISICOID` = T1.`INVACTIVOFIJOLUGARFISICOID`)
    LEFT JOIN `SECTOR` T11 ON T11.`LUGARFISICOID` = T1.`INVACTIVOFIJOLUGARFISICOID` AND T11.`SECTORID` = T1.`INVACTIVOFIJOSECTORID`)
    LEFT JOIN `CENTROALMACENAJE` T12 ON T12.`CENTROALMACENAJEID` = T1.`INVACTIVOFIJOCENTROALMACENAJEI`)
    INNER JOIN `PERIODO` T13 ON T13.`PERIODOID` = T1.`INVACTIVOFIJOPERIODOID`)
WHERE T1.`INVACTIVOFIJOID` = 2684912
ORDER BY T1.`INVACTIVOFIJOID`;

SELECT * from k2b_prod.CENTROALMACENAJE C;

SELECT * FROM k2b_prod.INVENTARIOACTIVOFIJO I WHERE I.INVACTIVOFIJOROLCODIGO=''