/*SELECT * FROM GXTRJDTA.tdgbin WHERE BINNROBIN LIKE '527607%'

INSERT INTO GXTRJDTA.TDGBIN
(BINNROBIN, BINDSBIN, BINNMCORTO, BINIDMARCA, BINIDPRODU, BINIDTUTRJ, BINAMBUSO, BINLONGBIN, BINLONGTRJ, BINULTNROT, BINPROCBPS, BINCVV, BINCVV2, BINESTBIN, BINESBINSW, BINUSUALTA, BINFECALTA, BINUSULTUP, BINFHULTUP, BINCODENT, BINCODAFI, BINMADRE, BINCODPRO, PAIIDPAIS, BINTOKEN, BINNROMADR, BINPARAMET)
VALUES('52760700    ', 'MASTERCARD BANCARD                                          ', '                              ', 'MST', 'BLK', 'C ', 'I', 8, 16, 0, 'N', 'S', 'N', 'A', 'A', 'MIGRACION ', '20200402', '          ', '0001-01-01 00:00:00.000', 9004, 0, 'S', 9000, 600, ' ', '            ', 'MIGRACION           ');

INSERT INTO GXTRJDTA.TDGBIN
(BINNROBIN, BINDSBIN, BINNMCORTO, BINIDMARCA, BINIDPRODU, BINIDTUTRJ, BINAMBUSO, BINLONGBIN, BINLONGTRJ, BINULTNROT, BINPROCBPS, BINCVV, BINCVV2, BINESTBIN, BINESBINSW, BINUSUALTA, BINFECALTA, BINUSULTUP, BINFHULTUP, BINCODENT, BINCODAFI, BINMADRE, BINCODPRO, PAIIDPAIS, BINTOKEN, BINNROMADR, BINPARAMET)
VALUES('54528800      ', 'MASTERCARD CONTINENTAL                                      ', '                              ', 'MST', 'ORO', 'C ', 'I', 8, 16, 0, 'N', 'S', 'N', 'A', 'A', 'MIGRACION ', '20200402', '          ', '0001-01-01 00:00:00.000', 9004, 0, 'S', 9000, 600, ' ', '            ', 'MIGRACION');

INSERT INTO GXTRJDTA.TDGBIN
(BINNROBIN, BINDSBIN, BINNMCORTO, BINIDMARCA, BINIDPRODU, BINIDTUTRJ, BINAMBUSO, BINLONGBIN, BINLONGTRJ, BINULTNROT, BINPROCBPS, BINCVV, BINCVV2, BINESTBIN, BINESBINSW, BINUSUALTA, BINFECALTA, BINUSULTUP, BINFHULTUP, BINCODENT, BINCODAFI, BINMADRE, BINCODPRO, PAIIDPAIS, BINTOKEN, BINNROMADR, BINPARAMET)
VALUES('54528900      ', 'MASTERCARD CONTINENTAL                                      ', '                              ', 'MST', 'ORO', 'C ', 'I', 8, 16, 0, 'N', 'S', 'N', 'A', 'A', 'MIGRACION ', '20200402', '          ', '0001-01-01 00:00:00.000', 9004, 0, 'S', 9000, 600, ' ', '            ', 'MIGRACION');

--UPDATE GXTRJDTA.TDGBIN SET BINIDPRODU='ORO' WHERE BINNROBIN='54528800'

INSERT INTO GXTRJDTA.TDGBIN
(BINNROBIN, BINDSBIN, BINNMCORTO, BINIDMARCA, BINIDPRODU, BINIDTUTRJ, BINAMBUSO, BINLONGBIN, BINLONGTRJ, BINULTNROT, BINPROCBPS, BINCVV, BINCVV2, BINESTBIN, BINESBINSW, BINUSUALTA, BINFECALTA, BINUSULTUP, BINFHULTUP, BINCODENT, BINCODAFI, BINMADRE, BINCODPRO, PAIIDPAIS, BINTOKEN, BINNROMADR, BINPARAMET)
VALUES('51079500      ', 'MASTERCARD CONTINENTAL                                      ', '                              ', 'MST', 'EMP', 'C ', 'I', 8, 16, 0, 'N', 'S', 'N', 'A', 'A', 'MIGRACION ', '20200402', '          ', '0001-01-01 00:00:00.000', 9004, 0, 'S', 9000, 600, ' ', '            ', 'MIGRACION');

INSERT INTO GXTRJDTA.TDGBIN
(BINNROBIN, BINDSBIN, BINNMCORTO, BINIDMARCA, BINIDPRODU, BINIDTUTRJ, BINAMBUSO, BINLONGBIN, BINLONGTRJ, BINULTNROT, BINPROCBPS, BINCVV, BINCVV2, BINESTBIN, BINESBINSW, BINUSUALTA, BINFECALTA, BINUSULTUP, BINFHULTUP, BINCODENT, BINCODAFI, BINMADRE, BINCODPRO, PAIIDPAIS, BINTOKEN, BINNROMADR, BINPARAMET)
VALUES('42241000      ', 'VISA CLASICA BCO. CONTINENTAL                                ', '                              ', 'VSA', 'CLA', 'C ', 'I', 8, 16, 0, 'N', 'S', 'N', 'A', 'A', 'MIGRACION ', '20200402', '          ', '0001-01-01 00:00:00.000', 9004, 0, 'S', 9000, 600, ' ', '            ', 'MIGRACION');

INSERT INTO GXTRJDTA.TDGBIN
(BINNROBIN, BINDSBIN, BINNMCORTO, BINIDMARCA, BINIDPRODU, BINIDTUTRJ, BINAMBUSO, BINLONGBIN, BINLONGTRJ, BINULTNROT, BINPROCBPS, BINCVV, BINCVV2, BINESTBIN, BINESBINSW, BINUSUALTA, BINFECALTA, BINUSULTUP, BINFHULTUP, BINCODENT, BINCODAFI, BINMADRE, BINCODPRO, PAIIDPAIS, BINTOKEN, BINNROMADR, BINPARAMET)
VALUES('42302700    ', 'VISA INFINITE CONTINENTAL                                   ', 'VISA INFINITE CONTI           ', 'VSA', 'IFT', 'C ', 'I', 8, 16, 0, 'N', 'N', 'N', 'A', 'A', 'MIGRACION ', '20200402', 'UPD_AUT010', '2022-12-01 11:51:43.000', 1020, 0, 'S', 9000, 600, ' ', '            ', 'MIGRACION');

INSERT INTO GXTRJDTA.TDGBIN
(BINNROBIN, BINDSBIN, BINNMCORTO, BINIDMARCA, BINIDPRODU, BINIDTUTRJ, BINAMBUSO, BINLONGBIN, BINLONGTRJ, BINULTNROT, BINPROCBPS, BINCVV, BINCVV2, BINESTBIN, BINESBINSW, BINUSUALTA, BINFECALTA, BINUSULTUP, BINFHULTUP, BINCODENT, BINCODAFI, BINMADRE, BINCODPRO, PAIIDPAIS, BINTOKEN, BINNROMADR, BINPARAMET)
VALUES('42241100    ', 'VISA ORO BCO. CONTINENTAL                                   ', 'VISA ORO CONTI                ', 'VSA', 'ORO', 'C ', 'I', 8, 16, 0, 'N', 'N', 'N', 'A', 'A', 'MIGRACION ', '20200402', 'UPD_AUT010', '2022-12-01 11:51:43.000', 1020, 0, 'S', 9000, 600, ' ', '            ', '                    ');

SELECT * FROM GXTRJDTA.tdgbin WHERE BINNROBIN LIKE '527607%'  */

MASTERCARD
UPDATE GXTRJDTA.tdgbin  SET BINLONGBIN = '8' , BINCODPRO = '9000' , BINPARAMET = 'MIGRACION' WHERE BINNROBIN = '527607'
UPDATE GXTRJDTA.tdgbin  SET BINLONGBIN = '8' , BINCODPRO = '9000' , BINPARAMET = 'MIGRACION' WHERE BINNROBIN = '545288'
UPDATE GXTRJDTA.tdgbin  SET BINLONGBIN = '8' , BINCODPRO = '9000' , BINPARAMET = 'MIGRACION' WHERE BINNROBIN = '545289'
UPDATE GXTRJDTA.tdgbin  SET BINLONGBIN = '8' , BINCODPRO = '9000' , BINPARAMET = 'MIGRACION' WHERE BINNROBIN = '510795'

VISA
UPDATE GXTRJDTA.tdgbin  SET BINLONGBIN = '8' , BINCODPRO = '9000' , BINPARAMET = 'MIGRACION' WHERE BINNROBIN = '422410'
UPDATE GXTRJDTA.tdgbin  SET BINLONGBIN = '8' , BINCODPRO = '9000' , BINPARAMET = 'MIGRACION' WHERE BINNROBIN = '423027'
UPDATE GXTRJDTA.tdgbin  SET BINLONGBIN = '8' , BINCODPRO = '9000' , BINPARAMET = 'MIGRACION' WHERE BINNROBIN = '422411'


SELECT * FROM FEATMSLIB.QAC6KEYST Q6P;

--Para MASTERCARD:
Ind Función Label
1 CPAD MASCPAD
1 CPE MASCPE
1 CVVD MASCVKD
1 CVVI MASCVKI
1 CV2D MASCVKD
1 CV2I MASCVKI
1 PIN MASPVK
1 PVV MASPVK
2 PVV MASPVK
1	 ICVD    MASCVD
1    ICVI    MASCVI

INSERT INTO FEATMSLIB.AZKRBL
(RBLBIN, RBLPKI, RBLFUN, RBLLBL, RBLFLG)
VALUES('545289 ', 1, 'ICVD ', 'MASCVD ', ' ');

INSERT INTO FEATMSLIB.AZKRBL
(RBLBIN, RBLPKI, RBLFUN, RBLLBL, RBLFLG)
VALUES('545289 ', 1, 'ICVI ', 'MASCVI ', ' ');

INSERT INTO FEATMSLIB.AZKRBL
(RBLBIN, RBLPKI, RBLFUN, RBLLBL, MASCPAD)
VALUES('545289 ', 1, 'CPAD ', 'MASCPAD ', ' ');

INSERT INTO FEATMSLIB.AZKRBL
(RBLBIN, RBLPKI, RBLFUN, RBLLBL, RBLFLG)
VALUES('545289 ', 1, 'CPE ', 'MASCPE ', ' ');

INSERT INTO FEATMSLIB.AZKRBL
(RBLBIN, RBLPKI, RBLFUN, RBLLBL, RBLFLG)
VALUES('545289 ', 1, 'CVVD ', 'MASCVKD ', ' ');

INSERT INTO FEATMSLIB.AZKRBL
(RBLBIN, RBLPKI, RBLFUN, RBLLBL, RBLFLG)
VALUES('545289 ', 1, 'CVVI ', 'MASCVKI ', ' ');

INSERT INTO FEATMSLIB.AZKRBL
(RBLBIN, RBLPKI, RBLFUN, RBLLBL, RBLFLG)
VALUES('545289 ', 1, 'CV2D ', 'MASCVKD ', ' ');

INSERT INTO FEATMSLIB.AZKRBL
(RBLBIN, RBLPKI, RBLFUN, RBLLBL, RBLFLG)
VALUES('545289 ', 1, 'CV2I ', 'MASCVKI', ' ');

INSERT INTO FEATMSLIB.AZKRBL
(RBLBIN, RBLPKI, RBLFUN, RBLLBL, RBLFLG)
VALUES('545289 ', 1, 'PIN ', 'MASPVK ', ' ');

INSERT INTO FEATMSLIB.AZKRBL
(RBLBIN, RBLPKI, RBLFUN, RBLLBL, RBLFLG)
VALUES('545289 ', 1, 'PVV ', 'MASPVK ', ' ');

INSERT INTO FEATMSLIB.AZKRBL
(RBLBIN, RBLPKI, RBLFUN, RBLLBL, RBLFLG)
VALUES('545289 ', 2, 'PVV ', 'MASPVK ', ' ');
------------------------------------------------
SELECT * FROM FEATMSLIB.AZKRBL WHERE RBLBIN ='46779100';

INSERT INTO FEATMSLIB.AZKRBL (RBLBIN, RBLPKI, RBLFUN, RBLLBL, RBLFLG) VALUES('46779100', 1, 'CPAD', 'CPAVISA ', '');
INSERT INTO FEATMSLIB.AZKRBL (RBLBIN, RBLPKI, RBLFUN, RBLLBL, RBLFLG) VALUES('46779100', 1, 'CPE ', 'CPEVISA ', '');
INSERT INTO FEATMSLIB.AZKRBL (RBLBIN, RBLPKI, RBLFUN, RBLLBL, RBLFLG) VALUES('46779100', 1, 'CVVD', 'CVVDVISA', '');
INSERT INTO FEATMSLIB.AZKRBL (RBLBIN, RBLPKI, RBLFUN, RBLLBL, RBLFLG) VALUES('46779100', 1, 'CVVI', 'CVVIVISA', '');
INSERT INTO FEATMSLIB.AZKRBL (RBLBIN, RBLPKI, RBLFUN, RBLLBL, RBLFLG) VALUES('46779100', 1, 'CV2D', 'CVVDVISA', '');
INSERT INTO FEATMSLIB.AZKRBL (RBLBIN, RBLPKI, RBLFUN, RBLLBL, RBLFLG) VALUES('46779100', 1, 'CV2I', 'CVVIVISA', '');
INSERT INTO FEATMSLIB.AZKRBL (RBLBIN, RBLPKI, RBLFUN, RBLLBL, RBLFLG) VALUES('46779100', 1, 'ICVD', 'CVVDVISA', '');
INSERT INTO FEATMSLIB.AZKRBL (RBLBIN, RBLPKI, RBLFUN, RBLLBL, RBLFLG) VALUES('46779100', 1, 'ICVI', 'CVVIVISA', '');
INSERT INTO FEATMSLIB.AZKRBL (RBLBIN, RBLPKI, RBLFUN, RBLLBL, RBLFLG) VALUES('46779100', 1, 'PIN ', 'PVKVISA ', '');
INSERT INTO FEATMSLIB.AZKRBL (RBLBIN, RBLPKI, RBLFUN, RBLLBL, RBLFLG) VALUES('46779100', 1, 'PVV ', 'PVKVISA ', '');
INSERT INTO FEATMSLIB.AZKRBL (RBLBIN, RBLPKI, RBLFUN, RBLLBL, RBLFLG) VALUES('46779100', 2, 'PVV ', 'VISADEC ', '');
--------------------------------------------
Para los bines nuevos de Mastercard, cargar sus labels ICVD y ICVI
**********************************************************************
INSERT INTO FEATMSLIB.AZKRBL
(RBLBIN, RBLPKI, RBLFUN, RBLLBL, RBLFLG)
VALUES('545289 ', 1, 'ICVD ', 'MASCVD ', ' ');

INSERT INTO FEATMSLIB.AZKRBL
(RBLBIN, RBLPKI, RBLFUN, RBLLBL, RBLFLG)
VALUES('545289 ', 1, 'ICVI ', 'MASCVI ', ' ');
*************************************************
INSERT INTO FEATMSLIB.AZKRBL
(RBLBIN, RBLPKI, RBLFUN, RBLLBL, MASCPAD)
VALUES('545289 ', 1, 'CPAD ', 'MASCPAD ', ' ');



INSERT INTO FEATMSLIB.AZKRBL
(RBLBIN, RBLPKI, RBLFUN, RBLLBL, RBLFLG)
VALUES('545289 ', 1, 'CPE ', 'MASCPE ', ' ');

INSERT INTO FEATMSLIB.AZKRBL
(RBLBIN, RBLPKI, RBLFUN, RBLLBL, RBLFLG)
VALUES('545289 ', 1, 'CVVD ', 'MASCVKD ', ' ');

INSERT INTO FEATMSLIB.AZKRBL
(RBLBIN, RBLPKI, RBLFUN, RBLLBL, RBLFLG)
VALUES('545289 ', 1, 'CVVI ', 'MASCVKI ', ' ');

INSERT INTO FEATMSLIB.AZKRBL
(RBLBIN, RBLPKI, RBLFUN, RBLLBL, RBLFLG)
VALUES('545289 ', 1, 'CV2D ', 'MASCVKD ', ' ');

INSERT INTO FEATMSLIB.AZKRBL
(RBLBIN, RBLPKI, RBLFUN, RBLLBL, RBLFLG)
VALUES('545289 ', 1, 'CV2I ', 'MASCVKI ', ' ');

INSERT INTO FEATMSLIB.AZKRBL
(RBLBIN, RBLPKI, RBLFUN, RBLLBL, RBLFLG)
VALUES('545289 ', 1, 'PIN ', 'MASPVK ', ' ');

INSERT INTO FEATMSLIB.AZKRBL
(RBLBIN, RBLPKI, RBLFUN, RBLLBL, RBLFLG)
VALUES('545289 ', 1, 'PVV ', 'MASPVK ', ' ');

INSERT INTO FEATMSLIB.AZKRBL
(RBLBIN, RBLPKI, RBLFUN, RBLLBL, RBLFLG)
VALUES('545289 ', 2, 'PVV ', 'MASPVK ', ' ');