--REDINIE
-- http://redmine2.bepsa.com.py/issues/43647
--TCUOTAF PRODU
CREATE or replace MASK msk_TCUOTAF ON  gxbdbps/TCUOTAF
FOR COLUMN  MTNUMTA     RETURN
CASE
WHEN (VERIFY_GROUP_FOR_USER(SESSION_USER,
'DBA', 'OPERNOC', 'VIEWTAR') = 1)
THEN MTNUMTA
WHEN POSSTR(MTNUMTA, 'TARJ;') = 1
THEN MTNUMTA
ELSE
SUBSTR(MTNUMTA, 1, 6)  ||'XXXXXX'|| SUBSTR(MTNUMTA, 13, 4)
END
ENABLE
ALTER TABLE GXBDBPS/TCUOTAF ACTIVATE column ACCESS CONTROL
-- LISTO OK
--THMOVAF PRODU
CREATE or replace MASK msk_THMOVAF ON  gxbdbps/THMOVAF
FOR COLUMN  HMNUMTA     RETURN
CASE
WHEN (VERIFY_GROUP_FOR_USER(SESSION_USER,
'DBA', 'OPERNOC', 'VIEWTAR') = 1)
THEN HMNUMTA
WHEN POSSTR(HMNUMTA, 'TARJ;') = 1
THEN HMNUMTA
ELSE
SUBSTR(HMNUMTA, 1, 6)  ||'XXXXXX'|| SUBSTR(HMNUMTA, 13, 4)
END
ENABLE
ALTER TABLE GXBDBPS/THMOVAF ACTIVATE column ACCESS CONTROL
--LISTO
--TGEMBHAF PRODU
CREATE or replace MASK msk_TGEMBHAF ON  LIBDEBITO/TGEMBHAF
FOR COLUMN  CRTARJ     RETURN
CASE
WHEN (VERIFY_GROUP_FOR_USER(SESSION_USER,
'DBA', 'OPERNOC', 'VIEWTAR') = 1)
THEN CRTARJ
WHEN POSSTR(CRTARJ, 'TARJ;') = 1
THEN CRTARJ
ELSE
SUBSTR(CRTARJ, 1, 6)  ||'XXXXXX'|| SUBSTR(CRTARJ, 13, 4)
END
ENABLE
ALTER TABLE LIBDEBITO/TGEMBHAF ACTIVATE column ACCESS CONTROL
--LISTO OK
--TDCTAAD
CREATE or replace MASK msk_TDCTAAD ON  gxbdbps/TDCTAAD
FOR COLUMN  TDADHNOMPLA     RETURN
CASE
WHEN (VERIFY_GROUP_FOR_USER(SESSION_USER,
'DBA', 'OPERNOC', 'VIEWTAR') = 1)
THEN TDADHNOMPLA
WHEN POSSTR(TDADHNOMPLA, 'TARJ;') = 1
THEN TDADHNOMPLA
ELSE
'NOMBRE APELLIDO'
END
ENABLE

ALTER TABLE GXBDBPS/TDCTAAD ACTIVATE column ACCESS CONTROL
LISTO OK
--TMOVPAG
CREATE or replace MASK msk_TMOVPAG ON  gxbdbps/TMOVPAG
FOR COLUMN  MPNTAR     RETURN
CASE
WHEN (VERIFY_GROUP_FOR_USER(SESSION_USER,
'DBA', 'OPERNOC', 'VIEWTAR') = 1)
THEN MPNTAR
WHEN POSSTR(MPNTAR, 'TARJ;') = 1
THEN MPNTAR
ELSE
SUBSTR(MPNTAR, 1, 6)  ||'XXXXXX'|| SUBSTR(MPNTAR, 13, 4)
END
ENABLE

ALTER TABLE GXBDBPS/TMOVPAG ACTIVATE column ACCESS CONTROL
--GCLIEAF
CREATE or replace MASK msk_gclieaf ON  gxbdbps/gclieaf
FOR COLUMN  CENOMB1     RETURN
CASE
WHEN (VERIFY_GROUP_FOR_USER(SESSION_USER,
'DBA', 'OPERNOC', 'VIEWTAR') = 1)
THEN CENOMB1
WHEN POSSTR(CENOMB1, 'TARJ;') = 1
THEN CENOMB1
ELSE
'NOMBRE1'
END
ENABLE
CREATE or replace MASK msk_gclieaf2 ON  gxbdbps/gclieaf
FOR COLUMN  CENOMB2     RETURN
CASE
WHEN (VERIFY_GROUP_FOR_USER(SESSION_USER,
'DBA', 'OPERNOC', 'VIEWTAR') = 1)
THEN CENOMB2
WHEN POSSTR(CENOMB2, 'TARJ;') = 1
THEN CENOMB2
ELSE
'NOMBRE2'
END
ENABLE
CREATE or replace MASK msk_gclieaf3 ON  gxbdbps/gclieaf
FOR COLUMN  CEAPEL1     RETURN
CASE
WHEN (VERIFY_GROUP_FOR_USER(SESSION_USER,
'DBA', 'OPERNOC', 'VIEWTAR') = 1)
THEN CEAPEL1
WHEN POSSTR(CEAPEL1, 'TARJ;') = 1
THEN CEAPEL1
ELSE
'APELLIDO1'
END
ENABLE
CREATE or replace MASK msk_gclieaf4 ON  gxbdbps/gclieaf
FOR COLUMN  CEAPEL2     RETURN
CASE
WHEN (VERIFY_GROUP_FOR_USER(SESSION_USER,
'DBA', 'OPERNOC', 'VIEWTAR') = 1)
THEN CEAPEL2
WHEN POSSTR(CEAPEL2, 'TARJ;') = 1
THEN CEAPEL2
ELSE
'APELLIDO2'
END
ENABLE
ALTER TABLE GXBDBPS/GCLIEAF ACTIVATE column ACCESS CONTROL
--TDCLIENTE
CREATE or replace MASK msk_TDCLI ON  gxbdbps/TDCLIENTE
FOR COLUMN  TDPRIMNOM     RETURN
CASE
WHEN (VERIFY_GROUP_FOR_USER(SESSION_USER,
'DBA', 'OPERNOC', 'VIEWTAR') = 1)
THEN TDPRIMNOM
WHEN POSSTR(TDPRIMNOM, 'TARJ;') = 1
THEN TDPRIMNOM
ELSE
'NOMBRE1'
END
ENABLE
CREATE or replace MASK msk_TDCLI2 ON  gxbdbps/TDCLIENTE
FOR COLUMN  TDSEGNOM     RETURN
CASE
WHEN (VERIFY_GROUP_FOR_USER(SESSION_USER,
'DBA', 'OPERNOC', 'VIEWTAR') = 1)
THEN TDSEGNOM
WHEN POSSTR(TDSEGNOM, 'TARJ;') = 1
THEN TDSEGNOM
ELSE
'NOMBRE2'
END
ENABLE
CREATE or replace MASK msk_TDCLI3 ON  gxbdbps/TDCLIENTE
FOR COLUMN  TDPRIMAPE     RETURN
CASE
WHEN (VERIFY_GROUP_FOR_USER(SESSION_USER,
'DBA', 'OPERNOC', 'VIEWTAR') = 1)
THEN TDPRIMAPE
WHEN POSSTR(TDPRIMAPE, 'TARJ;') = 1
THEN TDPRIMAPE
ELSE
'APELLIDO1'
END
ENABLE
CREATE or replace MASK msk_TDCLI4 ON  gxbdbps/TDCLIENTE
FOR COLUMN  TDSEGAPE     RETURN
CASE
WHEN (VERIFY_GROUP_FOR_USER(SESSION_USER,
'DBA', 'OPERNOC', 'VIEWTAR') = 1)
THEN TDSEGAPE
WHEN POSSTR(TDSEGAPE, 'TARJ;') = 1
THEN TDSEGAPE
ELSE
'APELLIDO2'
END
ENABLE
CREATE or replace MASK msk_TDCLI5 ON  gxbdbps/TDCLIENTE
FOR COLUMN  TDNOMAPE     RETURN
CASE
WHEN (VERIFY_GROUP_FOR_USER(SESSION_USER,
'DBA', 'OPERNOC', 'VIEWTAR') = 1)
THEN TDNOMAPE
WHEN POSSTR(TDNOMAPE, 'TARJ;') = 1
THEN TDNOMAPE
ELSE
'APELLIDO1, NOMBRE1'
END
ENABLE
ALTER TABLE GXBDBPS/TDCLIENTE ACTIVATE column ACCESS CONTROL
--TMOVIAF PRODU
CREATE or replace MASK msk_TMOVIAF ON  gxbdbps/TMOVIAF
FOR COLUMN  MTNUMTA     RETURN
CASE
WHEN (VERIFY_GROUP_FOR_USER(SESSION_USER,
'DBA', 'OPERNOC', 'VIEWTAR') = 1)
THEN MTNUMTA
WHEN POSSTR(MTNUMTA, 'TARJ;') = 1
THEN MTNUMTA
ELSE
SUBSTR(MTNUMTA, 1, 6)  ||'XXXXXX'|| SUBSTR(MTNUMTA, 13, 4)
END
ENABLE
ALTER TABLE GXBDBPS/TMOVIAF ACTIVATE column ACCESS CONTROL
--AIT002 PRODU
CREATE or replace MASK msk_AIT002 ON  gxbdbps/AIT002
FOR COLUMN  AITCTRJNRO     RETURN
CASE
WHEN (VERIFY_GROUP_FOR_USER(SESSION_USER,
'DBA', 'OPERNOC', 'VIEWTAR') = 1)
THEN AITCTRJNRO
WHEN POSSTR(AITCTRJNRO, 'TARJ;') = 1
THEN AITCTRJNRO
ELSE
SUBSTR(AITCTRJNRO, 1, 6)  ||'XXXXXX'|| SUBSTR(AITCTRJNRO, 13, 4)
END
ENABLE
ALTER TABLE GXBDBPS/AIT002 ACTIVATE column ACCESS CONTROL
--THEXTRAF PRODU
CREATE or replace MASK msk_THEXTRAF ON  gxbdbps/THEXTRAF
FOR COLUMN  HENUMTA     RETURN
CASE
WHEN (VERIFY_GROUP_FOR_USER(SESSION_USER,
'DBA', 'OPERNOC', 'VIEWTAR') = 1)
THEN HENUMTA
WHEN POSSTR(HENUMTA, 'TARJ;') = 1
THEN HENUMTA
ELSE
SUBSTR(HENUMTA, 1, 6)  ||'XXXXXX'|| SUBSTR(HENUMTA, 13, 4)
END
ENABLE
ALTER TABLE GXBDBPS/THEXTRAF ACTIVATE column ACCESS CONTROL
--TDCTA PRODU
CREATE or replace MASK msk_TDCTA ON  gxbdbps/TDCTA
FOR COLUMN  TDCTATAR     RETURN
CASE
WHEN (VERIFY_GROUP_FOR_USER(SESSION_USER,
'DBA', 'OPERNOC', 'VIEWTAR') = 1)
THEN TDCTATAR
WHEN POSSTR(TDCTATAR, 'TARJ;') = 1
THEN TDCTATAR
ELSE
SUBSTR(TDCTATAR, 1, 6)  ||'XXXXXX'|| SUBSTR(TDCTATAR, 13, 4)
END
ENABLE

ALTER TABLE GXBDBPS/TDCTA ACTIVATE column ACCESS CONTROL
--TMCTAAF PRODU
CREATE or replace MASK msk_TMCTAAF ON  gxbdbps/TMCTAAF
FOR COLUMN  MCNUMTA     RETURN
CASE
WHEN (VERIFY_GROUP_FOR_USER(SESSION_USER,
'DBA', 'OPERNOC', 'VIEWTAR') = 1)
THEN MCNUMTA
WHEN POSSTR(MCNUMTA, 'TARJ;') = 1
THEN MCNUMTA
ELSE
SUBSTR(MCNUMTA, 1, 6)  ||'XXXXXX'|| SUBSTR(MCNUMTA, 13, 4)
END
ENABLE
ALTER TABLE GXBDBPS/TMCTAAF ACTIVATE column ACCESS CONTROL
--TMTARAF PRODU
CREATE or replace MASK msk_tmtaraf ON  gxbdbps/tmtaraf
FOR COLUMN  MTNUMTA     RETURN
CASE
WHEN (VERIFY_GROUP_FOR_USER(SESSION_USER,
'DBA', 'OPERNOC', 'VIEWTAR') = 1)
THEN MTNUMTA
WHEN POSSTR(MTNUMTA, 'TARJ;') = 1
THEN MTNUMTA
ELSE
SUBSTR(MTNUMTA, 1, 6)  ||'XXXXXX'|| SUBSTR(mtnumta, 13, 4)
END
ENABLE
ALTER TABLE GXBDBPS/tmtaraf ACTIVATE column ACCESS CONTROL
--DRCONBEP PRODU
CREATE or replace MASK msk_drconbep ON  libdebito/drconbep
FOR COLUMN  LNRTAR     RETURN
CASE
WHEN (VERIFY_GROUP_FOR_USER(SESSION_USER,
'DBA', 'OPERNOC', 'VIEWTAR') = 1)
THEN LNRTAR
WHEN POSSTR(LNRTAR, 'TARJ;') = 1
THEN LNRTAR
ELSE
SUBSTR(LNRTAR, 1, 6)  ||'XXXXXX'|| SUBSTR(LNRTAR, 13, 4)
END
ENABLE
--VER por bloqueo
ALTER TABLE libdebito/drconbep ACTIVATE column ACCESS CONTROL
