/*datos personales*/
select * from gth.rhm100;
--delete from gth.rhm100;

SELECT * FROM gth.rhemple;
--update gth.rhemple set TBcodi = 1;


ALTER TABLE gth.EMPM100
ADD EmpVerHisJefe SMALLINT,
ADD EmpVerEstRec SMALLINT;

COMMENT ON COLUMN gth.EMPM100.EmpTipoPartTime IS 'Tipo part time   ';

COMMENT ON COLUMN gth.EMPM100.EmpVerHisJefe IS 'Ver historico de liq. del colaborador';

COMMENT ON COLUMN gth.EMPM100.EmpVerEstRec IS 'Ver columna Estado de Liquidaci�n';

SELECT * FROM GTH.RHMHLQ;

SELECT * FROM "GTHBEPSA".gth.RHEMPLE R WHERE R.FUNCNRO='5107555'; --FUNCIONARIOS
SELECT * FROM "GTHBEPSA".gth.RHMCRG R;
--datos laborales
SELECT
    TM1.FUNCESTAPR, TM1.FUNCTELCEL, T6.PERSONROALT AS FUNCNROALT, TM1.FUNCUSERAP, TM1.FUNCNROCUEPRE, TM1.FUNCSALBASE,
TM1.FUNCSALPAC, TM1.FUNCVIATICO, T4.EMPPRMBFMEDADCAJA, T4.EMPPRMBFMEDAD, TM1.EMPID, TM1.FUNCTURNOID AS FUNCTURNOID,
TM1.FUNCCCTID AS FUNCCCTID, TM1.TBCODI AS TBCODI, TM1.FUNCGRPTURNOID AS FUNCGRPTURNOID, TM1.GOURID, TM1.CARCOD,
TM1.CONTCARCOD AS CONTCARCOD, TM1.UNIORGCOD, TM1.RUBLIQ, TM1.SEGMECO, TM1.UNINEGO, TM1.DEPADMID, TM1.SECID,
TM1.CATCRGID, TM1.TFUNCCOD, TM1.SEGMEDID, TM1.SEGMEDTIPID, TM1.IMAID, TM1.BANCACOD, TM1.REFCOD, TM1.FUNCNRO AS FUNCNRO,
TM1.FUNCJEID AS FUNCJEID, TM1.FUNCMOTALTID AS FUNCMOTALTID, TM1.FUNCMOTBAJID AS FUNCMOTBAJID, T15.NIVJERCOD,
T15.AGRUCOD, T15.UNIORGEMPIDDEP AS UNIORGEMPIDDEP, T6.TDCID AS FUNCTDCID, T6.PERSOPAIID AS FUNCPAINACID, TM1.FUNCPERPRUFIN,
T4.EMPNOM, T4.EMPACRSUC,T6.PERSONOMB AS FUNCNOMB, T6.PERSOPRIAPEL AS FUNCPRIAPEL, T6.PERSOSEGAPEL AS FUNCSEGAPEL,
T6.PERSOPRINOM AS FUNCPRINOM, T6.PERSOSEGNOM AS FUNCSEGNOM, T6.PERSODIR AS FUNCDIR, T6.PERSOFECNAC AS FUNCFECNAC, T6.PERSOSEX AS FUNCSEXO,
T7.PAINAC AS FUNCPAINAC, T6.PERSOEDUCA AS FUNCEDUCA, T6.PERSOUNIVE AS FUNCUNIVE, T6.PERSOESTCIV AS FUNCESTCIV,
T6.PERSOMAIL AS FUNCMAIL, T6.PERSOCAT AS FUNCCAT, TM1.FUNCFECING, T6.PERSOUSERID AS FUNCUSERID, TM1.FUNCEST,
T8.TFUNCDES, T8.TFUNCAPORTA, T9.RUBDES, T10.CARDES, T10.CARFCCOND, T11.CATCRGDSC, T12.SEGMEDE,T13.DEPADMDSC,
T14.SECDSC, TM1.FUNCFRMPAG, TM1.FUNCTIPHOR, T15.UNIORGDES, T18.SUCNOM AS UNIORGEMPNOMDEP, T17.AGRUDES, T16.NIVJERDES,
T19.UNIDESC, TM1.FUNCNROLEG, TM1.FUNCTIPCTA, T20.BANCODES AS TBDESC, TM1.FUNCBANCO, TM1.FUNCFECREF, T21.SEGMEDDSC,
T22.SEGMEDTIPDSC, TM1.FUNCTIPSEG, TM1.FUNCFECSEG, TM1.FUNCNROREC, TM1.FUNCGRUSAN, TM1.FUNCENFER, TM1.FUNCNROASE,
TM1.FUNCENFER2, TM1.FUNCFECIPS, TM1.FUNCLESION, TM1.FUNCTRAANT, TM1.FUNCFECSAL, TM1.FUNCTIPBAJA, TM1.FUNCMOTBAJA,
TM1.FUNCOBSBAJA, T23.CCTESTADO AS FUNCCCTESTADO, TM1.FUNTARALM, T24.PERSONOMB AS FUNCJENOM, T24.PERSOUSERID AS FUNCJEUSR,
TM1.FUNCNROCLIENTE, TM1.FUNCNROINTERNO, TM1.FUNCNROFAX, TM1.FUNFINCO, TM1.FUNCPERFIL, TM1.FUNCEMPTERC, TM1.FUNCRAR,
TM1.FUNCRARANT, TM1.FUNCHABTC, TM1.FUNCNROTC, TM1.FUNCPORTC, TM1.FUNCAGRESC, TM1.FUNCNOMGUE, T25.CARDES AS CONTCARDES,
TM1.FUNCTELCORP, TM1.FUNCPROCED, T26.MOTALTBAJDSC AS FUNCMOTALTDSC, T26.MOTALTBAJTIP AS FUNCMOTALTTIP,
T27.MOTALTBAJDSC AS FUNCMOTBAJDSC, T27.MOTALTBAJTIP AS FUNCMOTBAJTIP, T28.TURNODSC AS FUNCTURNODSC,
T28.TURNOENT1 AS FUNCTURNOENT1, T28.TURNOCANT AS FUNCTURNOCANT, T28.TURNOSAL1 AS FUNCTURNOSAL1,
T28.TURNOSAL2 AS FUNCTURNOSAL2, T28.TURNOPOSHORMIN AS FUNCTURNOPOSHORMIN, T29.GRPTURNODSC AS FUNCGRPTURNODSC,
T2.BANCADSC, T3.REFDOMINIO, TM1.FUNCDIALIBRE, TM1.FUNCIRP, TM1.FUNCESTAP, TM1.FUNCFECAP, T5.GOURDSC, T10.CARRPO,
TM1.FUNCFECAPULT, TM1.FUNCUSERAPRU, TM1.FUNCSAUTORDNRO
FROM ((((((((((((((((((((((((((((GTH.RHEMPLE TM1 LEFT JOIN GTH.BANCA T2 ON T2.BANCACOD = TM1.BANCACOD) LEFT JOIN GTH.REFERENCIA T3 ON T3.REFCOD = TM1.REFCOD) INNER JOIN GTH.EMPM100 T4 ON T4.EMPID = TM1.EMPID) LEFT JOIN GTH.RHMGOURMET T5 ON T5.EMPID = TM1.EMPID AND T5.GOURID = TM1.GOURID) INNER JOIN GTH.RHM100 T6 ON T6.PERSONRO = TM1.FUNCNRO) LEFT JOIN GTH.BAMPAI T7 ON T7.PAIID = T6.PERSOPAIID) LEFT JOIN GTH.RHMTFC T8 ON T8.TFUNCCOD = TM1.TFUNCCOD) LEFT JOIN GTH.RHMCDC T9
                          ON T9.EMPID = TM1.EMPID AND T9.RUBLIQ = TM1.RUBLIQ) LEFT JOIN GTH.RHMCRG T10 ON T10.EMPID = TM1.EMPID AND T10.CARCOD = TM1.CARCOD) LEFT JOIN GTH.RHMCAT T11 ON T11.EMPID = TM1.EMPID AND T11.CATCRGID = TM1.CATCRGID) LEFT JOIN GTH.RHMSGM T12 ON T12.EMPID = TM1.EMPID AND T12.SEGMECO = TM1.SEGMECO) LEFT JOIN GTH.RHMDEP T13 ON T13.EMPID = TM1.EMPID AND T13.DEPADMID = TM1.DEPADMID) LEFT JOIN GTH.RHMSEC T14
                     ON T14.EMPID = TM1.EMPID AND T14.SECID = TM1.SECID) LEFT JOIN GTH.BAMUOG T15 ON T15.EMPID = TM1.EMPID AND T15.UNIORGCOD = TM1.UNIORGCOD) LEFT JOIN GTH.BAMNVJ T16 ON T16.NIVJERCOD = T15.NIVJERCOD) LEFT JOIN GTH.RHMAGR T17 ON T17.EMPID = TM1.EMPID AND T17.AGRUCOD = T15.AGRUCOD) LEFT JOIN GTH.EMPM200 T18 ON T18.EMPID = TM1.EMPID AND T18.SUCID = T15.UNIORGEMPIDDEP) LEFT JOIN GTH.RHMUNG T19 ON T19.EMPID = TM1.EMPID AND T19.UNINEGO = TM1.UNINEGO) LEFT JOIN GTH.BAMBAN T20
               ON T20.BANCOCOD = TM1.TBCODI) LEFT JOIN GTH.RHMSEG T21 ON T21.SEGMEDID = TM1.SEGMEDID) LEFT JOIN GTH.RHMSEGL1 T22 ON T22.SEGMEDID = TM1.SEGMEDID AND T22.SEGMEDTIPID = TM1.SEGMEDTIPID) LEFT JOIN GTH.RHMCCTB T23 ON T23.EMPID = TM1.EMPID AND T23.CCTID = TM1.FUNCCCTID) LEFT JOIN GTH.RHM100 T24 ON T24.PERSONRO = TM1.FUNCJEID) LEFT JOIN GTH.RHMCRG T25 ON T25.EMPID = TM1.EMPID AND T25.CARCOD = TM1.CONTCARCOD) LEFT JOIN GTH.RHMMOT T26
         ON T26.MOTALTBAJID = TM1.FUNCMOTALTID) LEFT JOIN GTH.RHMMOT T27 ON T27.MOTALTBAJID = TM1.FUNCMOTBAJID) LEFT JOIN GTH.RHMTURNO T28 ON T28.EMPID = TM1.EMPID AND T28.TURNOID = TM1.FUNCTURNOID) LEFT JOIN GTH.RHMGRPTURNO T29 ON T29.EMPID = TM1.EMPID AND T29.GRPTURNOID = TM1.FUNCGRPTURNOID)
/*WHERE --TM1.EMPID = 5107555
  --AND
TM1.FUNCNRO = 5107555*/
ORDER BY TM1.EMPID, TM1.FUNCNRO;
---liquidacion
SELECT T1.EMPID, T1.FUNCNRO AS FUNCNRO, T1.CLNROLIQ, COALESCE(T2.LQTOTDES, 0) AS LQTOTDES, COALESCE(T2.LQTOTHAB, 0) AS LQTOTHAB
FROM (GTH.RHMLIQ T1 LEFT JOIN (SELECT EMPID, CLNROLIQ, FUNCNRO, SUM(LQIMPREMU) AS LQTOTHAB, SUM(LQIMPDESC) AS LQTOTDES
FROM GTH.RHMLIQ10 GROUP BY EMPID, CLNROLIQ, FUNCNRO) T2 ON T2.EMPID = T1.EMPID AND T2.CLNROLIQ = T1.CLNROLIQ AND T2.FUNCNRO = T1.FUNCNRO)
WHERE T1.EMPID = '1'
  AND T1.FUNCNRO = '5107555'
  AND T1.CLNROLIQ = '633'
ORDER BY T1.EMPID, T1.FUNCNRO, T1.CLNROLIQ;

SELECT * FROM "GTHBEPSA".gth.RHMLIQ R WHERE R.LQFEC >='2024-10-30' AND R.FUNCNRO='5107555';
SELECT * FROM "GTHBEPSA".gth.RHEMPLE R; --FUNCIONARIOS
SELECT * FROM "GTHBEPSA".gth.RHM100 R; --PERSONAS
SELECT * FROM "GTHBEPSA".gth.RHMLIQ10 R --DETALLE DE LA LIQUIDACION
             WHERE R.EMPID = '1' AND R.CLNROLIQ='597';

---consulta empleado
select em.empid as "Cod. Empleado", r.personomb as "Nombre Completo", r.personro as "Nro Documento",
r.persomail as "Correo", em.carcod as "Cod Cargo", c.cardes as "Cargo", em.funcjeid as "Id Jefe Inmmediato",
em.funcest as "Estado"
from gth.rhemple em, gth.rhm100 r, gth.rhmcrg c
where em.funcnro = r.personro and em.carcod = c.carcod;

SELECT * FROM "GTHBEPSA".gth.RHMCRG R;
--DELETE FROM "GTHBEPSA".gth.RHMCRG R ;
SELECT * FROM "GTHBEPSA".gth.GDC002 G;
--DELETE from "GTHBEPSA".gth.GDC002 G;
-- RHMCRG y GDC002

alter table gth.almue10 add almdiasv numeric (2, 0);
alter table gth.almue10 add almdiasrs numeric (2, 0);
alter table gth.almue10 add almdiasp numeric (2, 0);
alter table gth.almue10 alter column almmrcinc type numeric (5, 2);
-----
SELECT * FROM gth.RHMLIQFIN R;
select * from gth.RHMLIQFINLOG R;

select LFDocCod from gth.rhmliqfin where funcnro = 4345348;
SELECT * FROM gth.gdc002 g WHERE TRIM(doccodchr) = '4345348';

select * from gth.rhmliqfin order by lffechliq desc;



DELETE FROM gth.rhemple
where funcnro = 4196976;

delete FROM gth.rhm100
where PersoNro = 4196976;
